In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
from pandas import DataFrame, Series
from __future__ import division # show flaoting number

### numpy

In [ ]:
np.set_printoptions(precision=2)
np.array([1.3333]) # show array([ 1.33])

np.nan #nan
np.inf #inf

np.array#([], dtype=np.float64(np.int32, np.string))#([[],[]])#([[[],[]],[[],[]]])
np.asarray#same as np.array

####################################
np.mgrid[0:3,0:2]
#array([[[0, 0],
#        [1, 1],
#        [2, 2]],
#       [[0, 1],
#        [0, 1],
#        [0, 1]]])

x = [-1,0,1]
y = [-2,0,-2]
xx, yy = np.meshgrid(x, y, sparse=True)
#xx : array([[-1,  0,  1]])
#yy : array([[-2],
#            [ 0],
#            [ 2]])
np.concatenate([x, y]) #array([-1,  0,  1, -2,  0, -2])
####################################
x = np.array([[1,2,3], [4,5,6]])
np.reshape(x,(3,2)) #array([[1, 2],[3, 4],[5, 6]])
np.transpose(x) #array([[1, 2],[3, 4],[5, 6]])
np.delete(x,2,1) # delete 2th col, axis=1 #array([[1, 2], [4, 5]])

x=np.arange(24).reshape((2,3,4))
#x=array([[[ 0,  1,  2,  3],
#          [ 4,  5,  6,  7],
#          [ 8,  9, 10, 11]],
#        [[12, 13, 14, 15],
#         [16, 17, 18, 19],
#         [20, 21, 22, 23]]])
x.transpose((0,2,1)) #the 1 and 2 axes exchage
x.swapaxes(1,2)
#array([[[ 0,  4,  8],
#        [ 1,  5,  9],
#        [ 2,  6, 10],
#        [ 3,  7, 11]],
#       [[12, 16, 20],
#        [13, 17, 21],
#        [14, 18, 22],
#        [15, 19, 23]]])

x =np.array([1,2,3,4,5,6,7,8])
np.array_split(x, 2) 
np.split(x, 2)       
#[array([1, 2, 3, 4]), array([5, 6, 7, 8])]
np.split(x, [2,5,7])  #[array([1, 2]), array([3, 4, 5]), array([6, 7]), array([8])]

np.ravel(x) 
x.flatten()
#array([1, 2, 3, 4, 5, 6])
np.repeat(x, 2) #array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])
np.repeat(x, [1, 2], axis=0)
#array([[1, 2, 3],
#       [4, 5, 6],
#       [4, 5, 6]])
np.tile(x,2)
#array([[1, 2, 3, 1, 2, 3],
#       [4, 5, 6, 4, 5, 6]])
np.tile(x, [2,3])
#array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
#       [4, 5, 6, 4, 5, 6, 4, 5, 6],
#       [1, 2, 3, 1, 2, 3, 1, 2, 3],
#       [4, 5, 6, 4, 5, 6, 4, 5, 6]])
####################################
x=np.array([1,2,3])
np.atleast_2d(x)#array([[1, 2, 3]])
x[np.newaxis,:] #array([[1, 2, 3]])

x = np.array([[1,2], [3,4]]); y= np.array([[10,20], [30,40]])
np.append(x,y)  #array([ 1,  2,  3,  4, 10, 20, 30, 40])
np.vstack((x,y))
np.r_[x,y]
np.append(x,y,axis=0)
np.concatenate((x, y), axis=0)
#array([[ 1,  2],
#       [ 3,  4],
#       [10, 21],
#       [30, 40]])
np.hstack((x,y))
np.c_[x,y]
np.column_stack((x,y))
np.append(x,y,axis=1)
np.concatenate((x, y), axis=1)
#array([[ 1,  2, 10, 20],
#       [ 3,  4, 30, 40]])

####################################
x = [1,2]
y = [3,4]
np.subtract.outer(x,y) #1-[3,4] , 2-[3,4]
#array([[-2, -3],
#       [-1, -2]])
np.add.outer(x,y)
#array([[4, 5],
#       [5, 6]])
np.multiply.outer(x,y)
#array([[3, 4],
#       [6, 8]])
np.divide.outer(x,y)
np.multiply.reduce(x) #1*2=2 #multiply values at the same axis

x = np.array([[1,2], [3,4]])
np.multiply.reduce(x, axis=0) #array([3, 8])
np.divide.reduce(x, axis=0) 
np.add.reduce(x, axis=0) 
np.subtract.reduce(x, axis=0) 
np.multiply.accumulate(x, axis=0) #array([[1, 2],[3, 8]])
np.divide.accumulate(x, axis=0)
np.add.accumulate(x, axis=0)
np.subtract.accumulate(x, axis=0)

x=[0, 1, 2, 3, 4, 5]
np.multiply.reduceat(x,[1,3], axis=0) #array([ 2, 60]) #2=x[1]*x[2], 60=x[3]*x[4]*x[5]
np.divide.reduceat(x,[1,3], axis=0)
np.add.reduceat(x,[1,3], axis=0)
np.subtract.reduceat(x,[1,3], axis=0)

np.logical_not([True, False, 0, 1]) #array([False,  True,  True, False], dtype=bool) # T become F, 0 become True
np.logical_and([True, True, False], [False, True, False])  #array([False,  True, False], dtype=bool)
np.logical_xor([True, True, False], [False, True, False]) #array([ True, False, False], dtype=bool)
np.logical_or([True, True, False], [False, True, False])  #array([ True,  True, False], dtype=bool)

x=np.array([[True, True, False],[False, True, False]])
np.logical_and.reduce(x, axis=0) #array([False,  True, False], dtype=bool)
np.logical_xor.reduce(x, axis=0) 
np.logical_or.reduce(x, axis=0)
np.where(x) #(array([0, 0, 1], dtype=int64), array([0, 1, 1], dtype=int64)) # show where is true

x=np.array([[0, 1], [2,0]])
np.where(x)  #(array([0, 1], dtype=int64), array([1, 0], dtype=int64))
np.where(x>0, 1,-1)
#array([[-1,  1],
#       [ 1, -1]])

np.in1d([1,2,3],[1,7]) #array([ True, False, False], dtype=bool)

np.isclose([1,2,3], 1) #array([ True, False, False], dtype=bool) check if array elements have 1
np.isclose([1,2,3], [1,2,5]) #array([ True,  True, False], dtype=bool)
x=np.array([[True,False],[True,True]])
np.all(x, axis=0) #check all array elements are True   check all array elements are True
np.any(x, axis=0) #array([ True,  True], dtype=bool)   check any array elements is True
x=np.array([[0,2],[3,np.nan]])
np.all(x, axis=0) #array([False,  True], dtype=bool)
np.any(x, axis=0) #array([ True,  True], dtype=bool

np.isnan([np.nan,1,2])            #array([ True, False, False], dtype=bool)
np.isfinite([np.nan,np.inf, 0,1]) #array([False, False,  True,  True], dtype=bool)
np.isinf([np.nan,np.inf, 0,1])    #array([False,  True, False, False], dtype=bool)

a=np.array([True,True,False]);b=np.array([3,6,9])
b[~a]  #show array([9])
b[a]   #show array([3, 6])
b==3   #show array([ True, False, False]
####################################
np.zeros(3)=np.empty(3) #array([ 0.,  0.,  0.])
np.zeros((2,3))=np.empty((2,3))
#array([[ 0.,  0.,  0.],
#       [ 0.,  0.,  0.]])
np.zeros_like([1,2,3]) #array([0, 0, 0]) return an array of zeros with the same shape of x
np.ones(3)  #array([ 1.,  1.,  1.])
np.ones((2,3))
np.eye(3)
#array([[ 1.,  0.,  0.],
#       [ 0.,  1.,  0.],
#       [ 0.,  0.,  1.]])
np.linspace(1, 2, num=5) #array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ])
np.logspace(1, 2, num=5) #array([  10.  ,   17.78,   31.62,   56.23,  100.  ])

np.arange(2,6) #array([2, 3, 4, 5])
np.arange(2,6,2) #array([2, 4])
np.arange(4).reshape((2,2))
#array([[0, 1],
#       [2, 3]])

x = [4, 3, 5, 7, 6, 8]
indices = [0, 1, 4]
np.take(x, indices) #array([4, 3, 6])

x = np.array([1,2,3,4,5])
np.put(x, [0, 2], [-44, -55])
x # array([-44,   2, -55,   4,   5])

x = np.array([0,1,2,3,4,5])
np.roll(x, 2)  #array([4, 5, 0, 1, 2, 3]) each element shift 2 position
####################################
import random

np.random.seed(0)#the seed for the next random number
random.seed(0)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
np.random.randn() # 1.764052345967664 #Return a sample value from the “standard normal”distribution (mean 0 and variance )
np.random.randn(2,2)
#array([[ 1.76,  0.4 ],
#       [ 0.98,  2.24]])
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
np.random.rand(2,2) # random samples from a uniform distribution over [0, 1)
#array([[ 0.44,  0.89],
#       [ 0.96,  0.38]])
random.random()    #0.8462617713735385 #show a number between 0-1 uniform distribution #can return 0 but not 1
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
np.random.randint(0,4, size=(2,2)) #each value is 0, 1, 2 or 3
#array([[2, 3],
#       [3, 2]]
random.randint(0,4)    #0  #0, 1, 2 or 3 
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
np.random.choice(5,3) #array([4, 2, 0]) show one value between 0, 1, 2, 3, 4
np.random.choice(5,3,replace=False) # draw sample without replacement
np.random.choice([1,2,4], 3) #array([1, 2, 2])
random.choice([1,2,4])       # show 1, 2 , or 4

import string
A=string.ascii_uppercase  #'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
A=string.ascii_lowercase#'abcdefghijklmnopqrstuvwxyz'
random.choice(A)          #'P'

random.sample(range(5),3)   #[3, 0, 4] # from 0,1,2,3,4 choose 3 values
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
np.random.normal(loc=0,scale=1, size=(3,3)) #scale is std
np.random.standard_normal(size=(3,3))    #Draw samples from a standard Normal distribution (mean=0, stdev=1).

random.gauss(mu=0, sigma=1)               # 0.7764926257342503
gaussiabsample=[random.gauss(mu=0, sigma=1) for i in range(100)]
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
np.random.exponential(scale=1.0, size=3) #Draw samples from an exponential distribution p(x)=(1/scale)exp(-x/scale)
np.random.uniform(-1,1,size=(3,3)) #a uniform distribution from -1 and 1
np.random.permutation(5) #array([4, 2, 0, 1, 3])
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x=np.array([1,2,3,4])
np.random.shuffle(x)
random.shuffle(x)
x #array([4, 1, 3, 2])
####################################
x = np.array([1,1,2])
np.unique(x) #array([1, 2])

x = np.array([[1,2,0],[0,4,5]])
np.argsort(x, axis=0)# show the index from the smallest value to the largest
#array([[1, 0, 0],
#       [0, 1, 1]], dtype=int64)
np.argmin(x, axis=0) #array([1, 0, 0], dtype=int64)
np.argmax(x, axis=0) #array([0, 1, 1], dtype=int64)
np.sort(x, axis=0) 
#array([[0, 2, 0],
#       [1, 4, 5]]

x = [1,2,2,3] 
y = [5,4,3,2] 
np.lexsort((y, x)) # Sort by x, then by y # list each element in x ranking (smallest =0), if the elements are the same, use y
array([0, 2, 1, 3], dtype=int64)
####################################
x = np.array([220,330,4])
bins = np.array([0,100,200,300])
np.digitize(x, bins)   
np.searchsorted(bins,x)
#array([3, 4, 1], dtype=int64)
np.searchsorted(bins, 110)  #2
np.searchsorted(bins, 100, side='left')  #1
np.histogram(x, bins)   #(array([1, 0, 1], dtype=int64), array([  0, 100, 200, 300]))=counts, bins

import bisect
A=[10,11,12,13,14]
bisect.bisect(A, 12.5)          #3  #find which index that 12.5 should be inserted to
bisect.insort(A,12.5)           #A become [10, 11, 12, 12.5, 13, 14]
bisect.bisect_left(A, 12.5)     #3
bisect.bisect_right(A, 12.5)    #4

x = np.array([220,330,40])
y = np.array([22,33,4])
binx = np.array([0,100,200,300])
biny = np.array([0,10,20,30])
np.histogram2d(x, y, bins=(binx, biny))
#(array([[ 1.,  0.,  0.],
#        [ 0.,  0.,  0.],
#        [ 0.,  0.,  1.]]),
# array([   0.,  100.,  200.,  300.]),
# array([  0.,  10.,  20.,  30.]))  =counts, binx, biny


x=np.array([0, 1, 1, 3, 3])
weight = np.array([0.1,0.2,0.3,0.4,0.5]) 
np.bincount(x)                     #array([1, 2, 0, 2], dtype=int64) Count number of occurrences of each value 
np.bincount(x,weight)              #array([ 0.1,  0.5,  0. ,  0.9])
np.bincount(x, weight, minlength=7) #array([ 0.1,  0.5,  0. ,  0.9,  0. ,  0. ,  0. ])
####################################
x = np.array([[1,2,3],[4,5,6]])
np.mean(x, axis=0)     #array([ 2.5,  3.5,  4.5])
np.average(x, axis=0)  #array([ 2.5,  3.5,  4.5])
np.median(x, axis=0)
np.std(x, axis=0)
np.var(x, axis=0)
np.ptp(x, axis=0) # array([3, 3, 3]) return max-min
np.sum(x, axis=0)
np.min(x, axis=0)
np.max(x, axis=0) 
np.diff(x, axis=0)  #array([[3, 3, 3]])
np.prod(x, axis=0) #array([ 4, 10, 18])
np.cumsum(x, axis=0)
#array([[1, 2, 3],
#       [5, 7, 9]])
np.cumprod(x, axis=0) 
#array([[ 1,  2,  3],
#       [ 4, 10, 18]])
np.apply_along_axis(lambda x:(x[0] + x[-1]) * 0.5,  1, x) #array([ 2.,  5.]) # 1 means axis=1

np.abs(x)
#array([[1, 2, 3],
#       [4, 5, 6]])
np.sqrt(x)
#array([[ 1.  ,  1.41,  1.73],
#       [ 2.  ,  2.24,  2.45]]
np.log(x)
np.log1p(x) #return log(1+x)

np.exp(x)
from scipy import exp
exp(x)

from scipy.special import expit#expit(z)=1/(1+exp(-z))
expit(x) #expit(x) = 1/(1+exp(-x)). 

np.expm1(x) #return exp(x)-1
np.diag(x)  #array([1, 5])
np.diag([1, 5]) 
#array([[1, 0],
#       [0, 5]])

x = np.array([[1,2,3],[4,5,6]])
np.percentile(x, 50)         #3.5
np.percentile(x, 50, axis=0) #array([ 2.5,  3.5,  4.5])
np.percentile(x, [25,50,75], axis=0)
#array([[ 1.75,  2.75,  3.75],
#       [ 2.5 ,  3.5 ,  4.5 ],
#       [ 3.25,  4.25,  5.25]])

np.modf([2.7, 3.5]) #(array([ 0.7,  0.5]), array([ 2.,  3.]))
np.maximum([2, 3, 4], [1, 5, 2]) #array([2, 5, 4])
np.sign([-5., 4.5])  #array([-1.,  1.])
np.floor([1.2,2.2,3.2]) #array([ 1.,  2.,  3.])

import math
math.ceil(2.3) #3
math.sqrt(2)
math.log(2)
math.factorial(4) #4!=24
####################################
x = [1,2,3,4]
y = [40,30,20,10]
np.corrcoef(x,y)  #return the correlation coefficient matrix of the variables
x = np.array([[1,2,3,4],[40,30,20,10]])
np.corrcoef(x)
#rray([[ 1., -1.],
#      [-1.,  1.]])
np.cov(x,y)      #return the covariance matrix of the variables
x = np.array([[1,2,3,4],[40,30,20,10]])
np.cov(x)
#rray([[   1.67,  -16.67],
#      [ -16.67,  166.67]])

x = np.array([[1,0],[0,2]])
#(1)
eigenvalues, eigenvectors=np.linalg.eig(x)
#(2)
from scipy.linalg import eigh
eigenvalues, eigenvectors=eigh(x)
eigenvalues  #array([ 1.,  2.])
eigenvectors 
#array([[ 1.,  0.],
#       [ 0.,  1.]])
np.linalg.inv(x)  # inverse of the matrix x
#array([[ 1. ,  0. ],
#       [ 0. ,  0.5]])

x = np.array([3,4])
np.linalg.norm(x)  #5
x = np.array([[3,0],[0,4]])
np.linalg.norm(x)  #5.0 # sqrt(3^2 +0+0+4^2)
np.linalg.norm(x,axis=0) #array([ 3.,  4.])  # (sqrt(3^2+0), sqrt(4^2+0))

x = np.array([10,20])
y = np.array([[1,2],
              [3,4]])
np.dot(x,y) 
x.T.dot(y)
#array([ 70, 100])

x = np.array([[1,2],[3,4]])
np.matrix(x)
#matrix([[1, 2],
#        [3, 4]])
np.matrix(x).T    #transpose matrix
#matrix([[1, 3],
#        [2, 4]])
np.matrix(x).I    #inverse matrix
#matrix([[-2. ,  1. ],
#        [ 1.5, -0.5]])
####################################
x = np.array([1,2])
y= np.array([3,4])
np.save('filename.npy', x)
np.load('filename.npy')

np.savetxt('filename.txt',x)
np.loadtxt('filename.txt')

np.save('filename.npz', ,a=x, b=y)
data=np.load('filename.npz') 
data['a'] #is x

y=x.copy()
####################################
x = np.array([1, 2, 2.5])
x.astype(int)   #array([1, 2, 2])
x.astype(float) #array([ 1. ,  2. ,  2.5])
x.astype(str)   #array(['1.0', '2.0', '2.5'])
x.dtype         #dtype('float64'
x.all()         #True #ask all true
x.any()         #True #ask any true
x.ndim          #1
x.shape         #(3L,)

x.shape[0]
len(x)          
#3
####################################
x=np.array([[1,2],[3,4],[5,6],[7,8]])
x[::2]# take every other row
#array([[1, 2],
#       [5, 6]])
x[::-1]#row sequence flip
#array([[7, 8],
#       [5, 6],
#       [3, 4],
#       [1, 2]])
x[:-1]#delete the last row
#array([[1, 2],
#       [3, 4],
#       [5, 6]])
x[0,1] #2

x=[1,2,3]
x[::-1]# return [3,2,1]

### Python Built-in Functions


In [373]:
x = [1, 2, 3]
y = [4, 5, 6]
zipped = zip(x, y)
zipped  #[(1, 4), (2, 5), (3, 6)]
a,b=zip(*zipped) #[(1, 2, 3), (4, 5, 6)]=a,b , a=(1,2,3)

x = ['A', 'B']
list(enumerate(x)) #[(0, 'A'), (1, 'B')]
list(enumerate(x, start=1)) #[(1, 'A'), (2, 'B')]

dict(one=1, two=2, three=3)  #{'one': 1, 'three': 3, 'two': 2}
dict(zip(['one', 'two', 'three'], [1, 2, 3]))
dict([('two', 2), ('one', 1), ('three', 3)])
dict({'three': 3, 'one': 1, 'two': 2})
#{'one': 1, 'three': 3, 'two': 2}
####################################
x=[1,3,2,4]
sorted(x)  #[1, 2, 3, 4]
sorted(x, reverse=True) #[4, 3, 2, 1]
#x=[[1,6,5],[2,3,10]]
sorted(x, key=lambda x: x[1]) #[[2, 3, 10], [1, 6, 5]]
sorted(['aaa','caa','baa'])  #['aaa', 'baa', 'caa']
sorted('ccaab')              #['a', 'a', 'b', 'c', 'c']
sorted(set('ccaab'))         #['a', 'b', 'c']

x=[1,3,2,4]
from random import random
sorted(x, key=lambda x: random()) #[1, 4, 3, 2] 
import random
random.shuffle(x)
x # [3, 2, 4, 1]

x=[1,3,2,4]
x.sort()
x # = [1, 2, 3, 4]

x = ['ab','bbb','b']
x.sort()
x # = ['ab', 'b', 'bbb']
x.sort(key=len)
x  # = ['b', 'ab', 'bbb'] 
x.sort(key=lambda x: len(set(list(x))))
x  # = ['b', 'bbb', 'ab']

list(reversed([1,4,5,2])) #[2, 5, 4, 1]
####################################
range(5) #[0, 1, 2, 3, 4]

x=[1,2,3]
sum(x)  #6
min(x)  #1
max(x)  #3
x=['aaa','b','cc']
max(x,key=len)  #'aaa'

7/3 #2.3333333333333335
7//3 #2
####################################
set([1,3,2,2])  #{1, 2, 3}
x = set(["a","a"])
y = set(["a","b"])
z = set(["a","c"])
f=(x,y,z) #f=({'a'}, {'a', 'b'}, {'a', 'c'})
set.intersection(*f)  #{'a'}
set.union(*f)         #{'a', 'b', 'c'}

{0, 1, 2}.issuperset({0, 1})   #True
{0, 1}.issubset({0, 1, 2})     #True
{0, 1, 2}.isdisjoint({3,4})    #True #see if these two sets have no elements in common
{0, 1}.union({0, 2, 5})#{0, 1, 2, 5} 
{0, 1}|{0, 2, 5}
{0, 1}.intersection({0, 2, 5})#{0} 
{0, 1}&{0, 2, 5}
{0, 1, 6}.difference({0, 2, 5})#{1, 6}
{0, 1, 6}-{0, 2, 5}
{0, 1, 6}.symmetric_difference({0, 2, 5})#{1, 2, 5, 6}     
{0, 1, 6}^{0, 2, 5}

frozenset([1,3,2,2])  #frozenset({1, 2, 3})
frozenset([1,2])|frozenset([1,3]) #frozenset({1,2,3})
frozenset([1,2])-frozenset([1,3]) #frozenset({2})
frozenset([1,2])&frozenset([1,3]) #frozenset({1})
frozenset([1,2])^frozenset([1,3]) #frozenset({2, 3})

0|0 #0
0|1 #1
1|1 #1
####################################
list('abc')  #['a', 'b', 'c']
tuple('abc') #('a', 'b', 'c')
x=tuple([1,2,3]) #'tuple' object does not support item assignment
x #(1, 2, 3)
x[0] #1

float(2) #show 2.0
int(2.3) #show 2
type(2)# show int
str(a)#'a'
bool()#(0),([]),(') return False #('a'),(1) return True

####################################
x={'a':1, 'b':2}
x.keys()   #['a', 'b']
x.values() #[1, 2]
x.items()  #[('a', 1), ('b', 2)]
x.get('a') # 1 
x.update({'c':3})
x['c'] = 3
x  # = {'a': 1, 'b': 2, 'c': 3}
del x['c']  #remove 'c': 3
'a' in x #True
list(iter(x))     
list(x.iterkeys())
#['a', 'b']

from collections import defaultdict
A=defaultdict(list) 
A['a'].append(1)  
A  #defaultdict(list, {'a': [1]})
A.items()#[('a', [1])]

#can used to tuple too , ie.(123, 'xyz','xyz')
C = [123, 'xyz','xyz'];
C.count('xyz') # 2
C.append([4, 5])# show [123, 'xyzxyz', 2009, [4, 5]]
C.append(4);C# show [123, 'xyzxyz', 2009, 4]
C.extend([4, 5, (1,2)])# C show [[123, 'xyz', 'xyz', 4, 5, (1, 2)]
C.insert(1, 'H1')#C become [123, 'H1', 'xyz', 'xyz'] insert 'HI' to index1
C.pop(1)
C.remove('xyz')
# C become [123, 'xyz']  remove the index 1
####################################
B='an book#pen'
B.replace('an','a') #show a book#pen
B.find('book')#3 show book the starting index# if B doesn't have book, it shows -1
B.startswith('an') #show True
B.split('#')# show ['an book', 'pen']#separate each token with #   #or (',')
B.split()# show ['an', 'book#pen']
B.isupper() #False #if B='BOOK', it will be True
'an' in B #True
B.index('b')#3
B.count('o')#2
B.upper()#'AN BOOK#PEN'

A='3';A.isdigit() #True
A='a';A.isdigit() #False
A='aa';A.isalpha() #True

x = ['a', 'b','c'];
'::'.join(x)   #'a::b::c'
x=' bc'
x.strip()      #'bc' #delete space
x='abc'
x[::-1]        #'cba'
####################################
def f(x):
    return x*2
f(4)#8
S=lambda x: x*2
S(4)

(1, 2, 3)

### Loop

In [ ]:
from collections import defaultdict
s = [('yellow', 1), ('blue', 2), ('yellow', 3), ('blue', 4), ('red', 1)]
d = defaultdict(list)
for k, v in s:
    d[k].append(v)
d  #defaultdict(list, {'blue': [2, 4], 'red': [1], 'yellow': [1, 3]})
###############
for _ in range(2):
for i in range(2):
for _ in xrange(200):#for very long range, recommand use xrange
    
for i in range(3):
    print i*i
#0
#1
#4
[x*x for x in range(3)] # [0, 1, 4]
###############    
x = ['A', 'B']
for i,j in enumerate(x):
    print i,j
#0 A
#1 B

x = [0, 1]
y = ['A', 'B']
for i, j in zip(x,y):
    print i,j
#0 A
#1 B 

x = np.array([[0,1],['A','B']])
for i in zip(*x):
    print i
#('0', 'A')
#('1', 'B'
x=[(1, 4), (2, 5), (3, 6)]
for i in zip(*x):
    print i
#(1, 2, 3)
#(4, 5, 6)  
###############
from itertools import combinations
for i in combinations([0,1,2], r=2):
    print i
#(0, 1)
#(0, 2)
#(1, 2)
###############
from itertools import product 
for i in product([0,1],[0,1]):
    print i
#(0, 0)
#(0, 1)
#(1, 0)
#(1, 1)
###############
import itertools
A=lambda x:x[0]
B=['abb', 'add', 'baa']
for i, j in itertools.groupby(B,A):
    print i, list(j)
#a ['abb', 'add']
#b ['baa']
###############
x={'a':1, 'b':2}
for i, j in x.items():
    print i, j
#a 1
#b 2
###############
df=DataFrame(['a','b'], columns=['A'])
for i, j in df['A'].iteritems():
    print i, j
#0 a
#1 b
###############
if true:
    ...
elif true:
    ...
else:
    ...
    
if true or true
###############
for i in [1,2,3]:
    if i ==2:
        break #when i=2, stop for loop
    print i
#1

for i in [1,2,3]:
    if i ==2:
        continue#skip i=2 loop
    print i
#1
#3

while x > 0:
    if i > 5:
        break
    i +=1
    print i
#1
#2
#3
#4
#5
#6
###############
A=[(1,2),(3,4)]
for i in A:
    for x in i:
        if x !=4:
            print x
#1
#2
#3
B=[x for i in A for x in i if x != 4]
B  #=[1, 2, 3]
###############
#fill a list value into a histogram
A={}
for i in [1,1,2,3,3]:
    A[i]=A.get(i,0) +1

from collections import Counter
A=Counter([1,1,2,3,3])

A  #= {1: 2, 2: 1, 3: 2}
###############
# A generator do not store all the values in memory, they generate the values on the fly.
# Yield is a keyword that is used like return, except the function will return a generator
def f():
    for i in range(3):
        yield i**2
        
F=f()# F is <generator object f at 0x000000000EC21900>
for i in F:
    print(i)
#0
#1
#4

### Regular expression operations

In [ ]:
import re
A='a b\t    c\t'
re.split('\s+',A)#['a', 'b', 'c', '']#seperate with more than one space
re.split('\s',A) #['a', 'b', '', '', '', '', 'c', '']
re.compile('\s+').split(A)#['a', 'b', 'c', '']#seperate with more than one space
re.compile('\s+').findall(A)#[' ', '\t    ', '\t']
############################################################################
B='lin10._%+-@yahoo.com, lin10@yahoo.com '
patten=r'[A-Z0-9._%+-]+@[A-z0-9]+.[A-z]{2,4}'
re.compile(patten, flags=re.IGNORECASE).findall(B)     # ['lin10._%+-@yahoo.com', 'lin10@yahoo.com']
#search the first email
f=re.compile(patten, flags=re.IGNORECASE).search(B)
B[f.start():f.end()]                                   #'lin10._%+-@yahoo.com' 
#replace email address with 'email'
re.compile(patten, flags=re.IGNORECASE).sub('email', B)#email, email 
############################################################################
patten1=r'([A-Z0-9._%+-]+)@([A-z0-9]+).([A-z]{2,4})'
re.compile(patten1, flags=re.IGNORECASE).findall(B)#[('lin10._%+-', 'yahoo', 'com'), ('lin10', 'yahoo', 'com')]
re.compile(patten1, flags=re.IGNORECASE).sub(r'X:\1,Y:\2,Z:\3',B)#'X:lin10._%+-,Y:yahoo,Z:com, X:lin10,Y:yahoo,Z:com '
#(r' \1 \2 \3',B)

A=DataFrame(['lin10@yahoo.com'], columns=['B'])
A['B'].str[:5]#0    lin10
A['B'].str.findall(patten1, flags=re.IGNORECASE)
#0    [(lin10, yahoo, com)]
#Name: B, dtype: object
A['B'].str.match(patten1, flags=re.IGNORECASE) 
#0    (lin10, yahoo, com)
#Name: B, dtype: object
A['B'].str.match(patten1, flags=re.IGNORECASE).str.get(1)  
#0    yahoo
#Name: B, dtype: object
############################################################################
patten2=r'(?P<X>[A-Z0-9._%+-]+)@(?P<Y>[A-z0-9]+).(?P<Z>[A-z]{2,4})'
f1=re.compile(patten2, flags=re.IGNORECASE)
f2=f1.match('wesm@yahoo.com')
f2.groupdict()#{'X': 'wesm', 'Y': 'yahoo', 'Z': 'com'}
#\s any whitespace character, includes ' ', \t, \n(newline), \r
#[] Used to indicate a set of characters, In a set:
# [a-z] means any lowercase letter; [0-9] means any number
#special characters lose their special meaning inside [].
# [._%+-] will match any of the literal characters '.', '_', '%', '+', '-'

# . mean  any character except a newline
# ^ mean the start of the string
# $ mean the end of the string or just before the newline at the end of the string
# *  match 0 or more repetitions 
# + match 1 or more repetitions 
# ? match 0 or 1 repetitions 
# {m} exactly m copies, ex: a{6} will match exactly six 'a' characters
#{m,n} match from m to n repetitions , ex: a{3,5} will match from 3 to 5 'a' characters.
# {m,n}? 
#(...) Matches whatever regular expression is inside the parentheses
#(?P<name>...) assign a group name
############################################################################
A=DataFrame(['aaa bbb 6p 480kg BIM 41'], columns=['B'])
#s(Series) can use like A'B] too
A['B'].str.extract('(\D*)', expand=False) 
#0    aaa bbb 
#Name: B, dtype: object 
A['B'].str.extract('(\D*)', expand=True) #return a table
#      0
#0  aaa bbb
A['B'].str.extract('.+\s(\D*) \d+$', expand=False)
#0    BIM
#Name: B, dtype: object
A['B'].str.extract('(\d+)p', expand=False)
#0    6
#Name: B, dtype: object
A['B'].str.extract('(\d+)(kg|g)', expand=False) #return a table
#    0  1
#0  480 kg
A['B'].map(lambda x: '_'.join([i for i in x.lower().split()]))
#0    aaa_bbb_6p_480kg_bim_41
#Name: B, dtype: object
A['B'].map(lambda x: ' '.join([i for i in x.lower().split()]))
#0    aaa bbb 6p 480kg bim 41
#Name: B, dtype: object 
A['B'].str.split(' ')
#0    [aaa, bbb, 6p, 480kg, BIM, 41]
#Name: B, dtype: object
A['B'].str.split(' ').str[0]
#0    aaa
#Name: B, dtype: object
A['B'].str.contains('p')
#0    True
#Name: B, dtype: bool

#() group together and show up
#*  0 or more
#+  more than 1
#\D  non digit characters
#\s space
#\d digit number
#. any character except new line
# $ the end of the string
# | or

### Print

In [ ]:
print '%.2f' % (2.3333)        #2.33
print '%s' % ('sd')            #sd
print '%10s' % ('sd')          #        sd # 10 spaces and sd 
print '%r' % ({'sd':1,'ee':2}) #{'ee': 2, 'sd': 1}
print'_%03d' % 3               #_003
print'%i' % 3.333              #3
print'%d' % 3.333              #3

print '{} {}'.format('one', 1)              #one 1
print '{:>10}'.format('test')               #      test# (align right)
print '{:10}'.format('test')                #test      #(align left)
print '{:_<10}'.format('test')              #test______
print '{:_>10}'.format('test')              #______test
print '{:^10}'.format('test')               #   test   #(align center)
print '{:.5}'.format('xylophone')           #xylop
print '{:10.5}'.format('xylophone')         #xylop     #(align left)
print '{:d}'.format(42)                     #42   #format number in integer
print '{:f}'.format(3.14159265358)          #3.141593#float
print '{:.3f}'.format(3.14159265358)        #3.142
print '%.2f' % (2.3333)                     #2.33
print ('%.2f' % (2.3333)).rjust(8)          #   2.33    #8 length string

### Open a file

In [ ]:
#'test.csv'
#   A   B
#0  1  10
#1  2  20
with open ('test.csv','r') as f: 
    B=f.read()  #'A,B\n1,10\n2,20\n'
    
list(open('test.txt'))#('xx.stdout')
#['A\tB\n', '1\t10\n', '2\t20\n']
####################################
import csv
with open('test.csv', 'rb') as f:
    reader = csv.reader(f)
    for row in reader:
        print row
#['A', 'B']
#['1', '10']
#['2', '20']
####################################
x=[]
with open ('test.csv', 'rb') as f:
    A=csv.reader(f)
    row=A.next()
    featurename=np.array(row) #array(['A', 'B']
    for i in A:
        x.append(i)
x=np.array(x) 
x #array([['1', '10'],
  #       ['2', '20']], 
####################################
f=open('test.csv')
reader=csv.reader(f)
for line in reader:
    print line
#['A', 'B']
#['1', '10']
#['2', '20']
lines=list(reader)
header, values=lines[0], lines[1:]
data_dict={columnname: columnvalues for columnname, columnvalues in zip(header, zip(*values))}
data_dict #{'A': ('1', '2'), 'B': ('10', '20')}

f=open('test.txt')
lines=f.readlines()
for i in lines:
    A=i.strip().split('\t') #if i is 'ap\t bo\t la\n', show ['ap',' bo','la'] #strip() delete line terminator \n
    print A
#['A', 'B']
#['1', '10']
#['2', '20']

###################################
df=pd.read_csv('.csv', sep=',', delimiter=None, header='infer'(None), usecols=['column1name','column2name'], 
index_col='column1name',prefix=None,dtype=None
skiprows=[0,2], nrows=5, na_values=['NuLL'],chunksize=1000, parse_date=True)

#sep=',' or '\s+'(separate with a space) or'\t' separate with a tab
#index_col=#0, the first column become index#index_col='column1name', the unique values of column1 become the index level
#usecols= [0, 1, 2] or [‘foo’, ‘bar’, ‘baz’]#pick the selected column
#header=None show no column names
#skiprows=[0,2] skip the first and third rows
#na_values=['NuLL'], if any missing value, mark it as NaN
#parse_date=True : date format become 1990-02-01, and date column become index 
#nrows=5 only show the first 5 rows
#if reading a csv file has momery difficulty, need to define chuncksize, and then:
df2 = pd.concat([chunk for chunk in df])

df=pd.read_table('test.csv', sep=',')
Series.from_csv('test.csv')
#A     B
#1    10
#2    20
#dtype: object

data=pd.ExcelFile('test.xlsx')
f=data.parse('test') #see the data in the first sheet 'test'
#   A  B
#0  1 10
#1  2 20
###################################
#if f=imag001-0016.png
f[3:f.index('-')] #will show 001
###################################
import json
json_data = open("file name")
data = json.load(json_data)
df=DataFrame(data)
###################################
import gzip
f = gzip.open('file.txt.gz', 'rb')
file_content = f.read()

with gzip.open('file.txt.gz','r') as f:
    for line in f: 
        print('got line', line)
        
from gzip import GzipFile
data=[k for k in A.split() for A in GzipFile('file.txt.gz')]
###################################
from io import StringIO
X=''' A, B
      1, 10
      2, 20'''
X=unicode(X)
pd.read_csv(StringIO(X)) # become a table
#  A   B
#0 1  10
#1 2  20
###################################
import glob
for i in glob.glob('C:\Python27\Scripts\Anaconda2/*.txt'):
          print i
#C:\Python27\Scripts\Anaconda2\SentiWordNet_3.0.0_20130122.txt
#C:\Python27\Scripts\Anaconda2\test.txt
filelist=glob.glob('C:\Python27\Scripts\Anaconda2/*.txt')
filelist
#['C:\\Python27\\Scripts\\Anaconda2\\SentiWordNet_3.0.0_20130122.txt',
# 'C:\\Python27\\Scripts\\Anaconda2\\test.txt']
###################################
import os
for dir_path, dir_name, files in os.walk('train/'):
    for f in files:
    #for f in files if f.endswith('.png')
        image=os.path.join(dir_path, f) 
        A=mh.imread(image)
###################################        
import os
path='C:\Python27\Scripts\Anaconda2'
filename= 'test.csv'
os.path.join(path,filename) 
os.path.abspath(path+'/'+filename)
#'C:\\Python27\\Scripts\\Anaconda2\\test.csv'

os.listdir(path)            # list all files in that directory
os.chdir(path)              # go to one directory
os.path.dirname(path)       #'C:\\Python27\\Scripts'    #Return the directory name of pathname path
os.path.exists(filename)    #True         #This file is existed in the current diectory
os.getcwd()                 #'C:\\Python27\\Scripts\\Anaconda2'  # current directory
os.path.splitext('C:\\Python27\\Scripts\\Anaconda2\\test.csv') #('C:\\Python27\\Scripts\\Anaconda2\\test', '.csv')
os.remove(filename)

### Write a file

In [ ]:
data = [
    ['Dan', 42],
    ['Cordelia', 33]
]
import csv
with open('test.csv', 'w') as outfile:
    mywriter = csv.writer(outfile, lineterminator='\n')
    mywriter.writerow(['name', 'age']) #add header
    for d in data:
        mywriter.writerow(d)
# test.csv become
#   name     age
#0  Dan      42
#1 Cordelia  33
#########JSON data (JAVASCRIPT object notation)
data={'column1name':[1,2],'column2name':[3,4]}
import json
json_data=json.dump(data)
##############################################
# Save very large data array on disk as an in-memory array
data = np.arange(4, dtype='float32').reshape(2,2)
mmap=np.memmap('filename', dtype='float64', mode='w+', shape=(2,2))
mmap[:] = data[:]
mmap.flush()
del mmap
# Open an existing memory map
mmap=np.memmap('filename',mode='r', dtype='float64', shape=(2,2))

### Matplotlib

In [ ]:
fig, ax=plt.subplots(nrows=1,ncols=1, figsize=(5,5), facecolor='white',sharex=True, sharey=True)
x=[1,2,3,4]
y=[1,4,9,16]
ax.plot(x,y, ls='--',lw=1,marker='.',alpha=0.8,label='data',color='k');
#aipha=(1: darkest),
#drawstyle='step-post',
#hold=True ( for adding more plots on the same graph),   
#color='k'(black),‘b’(blue),‘g’(green),‘r’(red),‘c’(cyan),‘m’(magenta),‘y’(yellow),‘w’(white)
#marker=”.”(point),“o”(circle),“v”(triangle_down),“^”(triangle_up),“<”(triangle_left),“>”(triangle_right),“8”(octagon)
#,“s”(square),“p”(pentagon),“*”(star),“D”(diamond)
plt.plot(x, y, drawstyle='steps-post') #drawstyle='steps-mid', 'steps-pre', 'steps-post' #step function
ax.semilogx(x,y); #a plot with log scaling on the x axis.
ax.semilogy(x,y); #a plot with log scaling on the y axis.
ax.scatter(x,y);
ax.scatter(x,y, c=x,cmap=plt.get_cmap('RdBu')) # scatter points have different colors
#cmap=plt.cm.RdYlGn,plt.cm.Blues,cmap=plt.cm.BrBG,cmap=plt.cm.Greens,plt.cm.RdGy,plt.cm.YlOrRd,plt.cm.autumn,plt.cm.binary,plt.cm.gist_earth,
#plt.cm.gist_heat,plt.cm.hot,plt.cm.spring,plt.cm.summer,plt.cm.jet,plt.cm.Spectral_r
ax.axvline(x=2,ymin=0.58, ymax = 0.79, color='r', linestyle='--', lw=2) # draw a vertical line
ax.hlines(y=2, xmin=-10, xmax=50, lw=2); # draw a horizontal line
ax.set_xticks([0,10,20,30]);
ax.set_yticks([0,10,20,30]);
ax.set_xticklabels(['a','b','c','d'], rotation=90, fontsize=10);
ax.set_yticklabels
ax.set_xscale('log')
ax.set_yscale('log')
ax.set_xlim(0,100)
ax.set_ylim(0,100)
ax.axis([0, 100, 0, 50]) # xlim=(0,100), ylim=(0,50)
ax.set_xlabel('xlabel')
ax.set_ylabel('ylabel')
ax.set_title('This is the title', fontsize='large')
ax.legend(loc='best')
#‘upper right’,‘upper center’,‘upper left’,‘lower left’,‘lower center’,‘lower right’,
#‘center’,‘center left’,‘center right’,‘right’,
ax.grid(True)
ax.text(2.5, 2, r'$\mu=100,\ \sigma=15$', bbox=dict(facecolor='red', alpha=0.5), fontsize=12) #(xposition, yposition
ax.annotate('local max', xy=(2, 3), xytext=(3, 1.5),  #add arrow and text to a data point 
             arrowprops=dict(facecolor='black', shrink=0.05)) 
#xytext is the text location(xposition,yposition)
#xy is the arrow final point location(xposition,yposition)

# delete all edges
for i in ax.spines.values():
    i.set_visible(False)

# set the xtick format
for tick in ax.xaxis.get_ticklabels():
    tick.set_fontsize('large')
    tick.set_fontname('Times New Roman')
    tick.set_color('blue')
    tick.set_weight('bold')
    
fig.tight_layout()

# Close the figure 
plt.close(fig) #plt.close('all')
######################  bar #######################################
objects = ('A', 'B', 'C')
y_pos = np.arange(len(objects))
x = [10,8,6]
ax.bar(y_pos, x, align='center', alpha=0.5,height=0.4, color='g',label='data')
ax.set_xticks(y_pos);
ax.set_xticklabels(objects);

ax.barh(y_pos, x, align='center', alpha=0.5,height=0.4, color='g',label='data')
ax.set_yticks(y_pos);
ax.set_yticklabels(objects);

df = pd.DataFrame([[5,10],[10,20],[5,9]])
df.plot(kind='bar',ax=ax, stacked=True)
######################  boxplot ######################################
x1 = np.random.normal(0,1,50)
x2 = np.random.normal(1,1,50)
x3 = np.random.normal(2,1,50)
bp = ax.boxplot([x1,x2,x3], patch_artist=True)
for box in bp['boxes']:
    # change outline color
    box.set( color='#7570b3', linewidth=2)
    # change fill color
    box.set( facecolor = '#1b9e77' )

## change color and linewidth of the whiskers
for whisker in bp['whiskers']:
    whisker.set(color='#7570b3', linewidth=2)

## change color and linewidth of the caps
for cap in bp['caps']:
    cap.set(color='#7570b3', linewidth=2)

## change color and linewidth of the medians
for median in bp['medians']:
    median.set(color='#b2df8a', linewidth=2)

## change the style of fliers and their fill
for flier in bp['fliers']:
    flier.set(marker='o', color='#e7298a', alpha=0.5)
    
ax.set_xticklabels(['Sample1', 'Sample2', 'Sample3'])
####################   hist   #######################################
x = np.random.randn(1000)
bins = np.linspace(-5, 5, 50)
ax.hist(x, bins, alpha=0.5,normed=1);

df = pd.DataFrame(np.random.randn(100), columns=['A'])
df['A'].plot(kind='hist', ax=ax)
df['A'].plot(kind='kde', ax=ax, secondary_y=True) #kernel density estimate
#######################  pie #########################################
labels = 'Frogs', 'Hogs', 'Dogs', 'Logs'
sizes = [15, 30, 45, 10]  # proportion
explode = (0, 0.1, 0, 0)  # only "explode" the 2nd slice (i.e. 'Hogs')
ax.pie(sizes, explode=explode, labels=labels, autopct='%1.1f%%',shadow=True, startangle=90)
ax.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
###################### contourf  ######################################
xlist = np.linspace(-3.0, 3.0, 100)
ylist = np.linspace(-3.0, 3.0, 100)
X, Y = np.meshgrid(xlist, ylist)
Z = np.sqrt(X**2 + Y**2)
colors=["red", "orange", "gold", "limegreen", "k", 
        "#550011", "purple", "seagreen"]
cmap = ListedColormap(colors)
g =ax.contourf(X, Y, Z, cmap=cmap)
plt.colorbar(g)
###################### spectram  ######################################
x = np.cumsum(np.random.random(1024) - 0.2)
data, freqs, bins, im =ax.specgram(x, NFFT=128, Fs=44100, noverlap=0,cmap='plasma',xextent=(0,30))
#Fs is the sample rate. x axis is time(sec), y axis is frequency intensity (Hz)
#the frequency is converted by fast fourier transform
###################### a hexagonal binning plot  ######################
x = np.random.standard_normal(10000)
y = 2.0 + 3.0 * x + 4.0 * np.random.standard_normal(n)
xmin = x.min()
xmax = x.max()
ymin = y.min()
ymax = y.max()
hb = ax.hexbin(x, y, gridsize=50, cmap='inferno')
ax.axis([xmin, xmax, ymin, ymax])
cb = fig.colorbar(hb, ax=ax)
#cmap=matplotlib.cm.Blues
#gridsize: The number of hexagons in the x-direction, default is 100
#a 2-D histogram with hexagonal cells and color each cell according to how many data in this cell. 
#It can be much more informative than a scatter plot
###################Rectangle, circle, Polygon  ######################
for p in [plt.Rectangle((0.1, 0.1), 0.3, 0.6,hatch='/'),
          plt.Rectangle((0.5, 0.1), 0.3, 0.6,hatch='\\',fill=False)]:
    ax.add_patch(p)
#((xpoition_of_bottomleftcorner,ypoition_of_bottomleftcorner ), rectanglewidth, rectanglelength)

circle1 = plt.Circle((0.5, 0.5), 0.2, color='blue')
circle2 = plt.Circle((1, 1), 0.2, color='g', clip_on=False)
ax.add_artist(circle1)
ax.add_artist(circle2)
#((xposition_of_center,yposition_of_center ), radius)

rect = plt.Rectangle((0.2, 0.75), 0.4, 0.15, color='k', alpha=0.3)
circ = plt.Circle((0.7, 0.2), 0.15, color='b', alpha=0.3)
pgon = plt.Polygon([[0.15, 0.15], [0.35, 0.4], [0.2, 0.6]],color='g', alpha=0.5) ##([x1,y1],[x2,y2],[x3,y3])
ax.add_patch(rect)
ax.add_patch(circ)
ax.add_patch(pgon)
################### plot an image  #################################
img=plt.imread('test.jpg') #Importing image data into Numpy arrays
plt.imshow(img) #(image, cmap='Set3'('Greys', plt.cm.gray,plt.cm.gray_r), extent=[xmin, xmax,ymin,ymax],interpolation='nearest')
plt.colorbar()

from IPython.display import Image
Image('test.jpg')
################### fill_between  #################################
X  = np.linspace(0,3,200)
Y1 = X**2 + 3
Y2 = np.exp(X) + 2
ax.plot(X,Y1,lw=4)
ax.plot(X,Y2,lw=4)
ax.fill_between(X, Y1,Y2,color='k',alpha=.5) #filling the regions between y1 and y2 
################### matshow  #################################
x = [[4,2,3],[4,2,5]]
ax.matshow(x, cmap=plt.cm.Spectral_r, interpolation='none');# Heatmap
################### add_subplot  #################################
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)

fig = plt.figure()
ax1 = fig.add_subplot(221)   #top left
ax2 = fig.add_subplot(222)   #top right
ax3 = fig.add_subplot(223)   #bottom left
ax4 = fig.add_subplot(224)   #bottom right 
################### add another plot #################################
# add another plot on the existed plot. A new plot position can be adjusted
x=[1,2,3,4]
y=[1,4,9,16]
ax = fig.add_axes([0.5, 0.5, 1., 1.,])#(xmin, ymin, dx, and dy) for the subplot,
ax.plot(x,y); 
#xmin and ymin are the coordinates of the lower left corner of the subplot, 
#dx and dy are the width and height of the subplot, with all values specified in relative units
#where 0 is left/bottom and 1 is top/right
################### y has two different scale axis for two curve #######
fig = plt.figure()
ax1 = fig.add_subplot(1, 1, 1)
ax2 = ax1.twinx()
t = np.linspace(0., 10., 100)
ax1.plot(t, t ** 2, 'b-')
ax2.plot(t, 1000 / (t + 1), 'r-')
ax1.set_ylabel('Density (cgs)', color='red')
ax2.set_ylabel('Temperature (K)', color='blue')
ax1.set_xlabel('Time (s)')
################### save a plot into a file############################
fig.savefig('myplot.eps', bbox_inches='tight')

### Pandas

In [ ]:
pd.DataFrame({'column1name':[1,2],'column2name':[3,4]})
#   column1name  column2name
#0       1          3
#1       2          4

pd.DataFrame({'column1name':Series([1,2], index=['a','b']),'column2name':Series([10,20], index=['b','c'])})
#   column1name   column2name
#a     1.0          NaN
#b     2.0          10.0
#c     NaN          20.0

pd.DataFrame({'column1name':{'index1':1, 'index2':2},'column2name':{'index1':3, 'index2':4}}, dtype='float')
pd.DataFrame([[1,2],[3,4]],index=['index1','index2'],
             columns=['column1name','column2name'], dtype='float')
#         column1name  column2name  
#index1      1.0         2.0
#index2      3.0         4.0


pd.DataFrame([[1,2],[3,4]],index=pd.Index(['index1','index2'], name='indexlevel'),
             columns=pd.Index(['column1name','column2name'], name='columnlevel'), dtype='float')
#columnlevel  column1name  column2name
#indexlevel
#index1         1.0         2.0
#index2         3.0         4.0

pd.DataFrame([[1,2],[3,4]],index=pd.Index(['index1','index2'], name='indexlevel'),
             columns=pd.MultiIndex.from_arrays([['level1x','level1y'],['level2x','level2y']], 
            names=['level1name', 'level2name']), dtype='float')
#level1name    level1x    level1y
#level2name    level2x    level2y
#indexlevel
#index1         1.0         2.0
#index2         3.0         4.0

df=pd.DataFrame([1,2,3,4],
                index=pd.MultiIndex.from_tuples([('one', 'a'), ('one', 'b'),('two', 'a'), ('two', 'b')]))
#          0
#one  a   1.0
#     b   2.0
#two  a   3.0
#     b   4.0

from collections import defaultdict
A=defaultdict(dict)
A['column1']['index1']=10;#B[columnindex][index]
A       #defaultdict(dict, {'column1': {'index1': 10}})
df=pd.DataFrame(A)
#        column1
#index1  10

pd.Series({'indexa':1,'indexb':2},index=['indexa','indexb'])
pd.Series({'indexa':1,'indexb':2})#
pd.Series([1,2],index=['indexa','indexb'])
#indexa    1
#indexb    2
pd.Series([1,2],index=[['indexa','indexb'],['index1','index2']])
#indexa  index1    1
#indexb  index2    2
####################################################################################
df.head#() #or (10)
df.tail#()#only show the last 5 rows
df.sample#(n=100) randomly pick up 100 rows
df.describe()#show count, mean, std, min, 25%, 50%, 75%, max for each column

pd.set_option('display.max_row',None)#dispay all the rows
pd.set_option('display.max_columns',None)
####################################################################################
df=pd.DataFrame([[1,2],[2,4]],columns=['column1name','column2name'], dtype='float')
df.to_csv('--.csv, index=False)
df.to_csv('xx.stdout', na_rep='NULL', sep='|', index=False, header=False) 
#if there is a missing value, mark it as NULL
x=df.to_dict()
x # {'column1name': {0: 1.0, 1: 2.0}, 'column2name': {0: 2.0, 1: 4.0}}
df1=df.copy()
####################################################################################                  
df=pd.DataFrame([[1,2],[3,4]],index=['index1','index2'],
             columns=['column1name','column2name'], dtype='float')
df[['column1name','column2name']]
df
#         column1name  column2name  
#index1      1.0         2.0
#index2      3.0         4.0

df.info()
#Index: 2 entries, index1 to index2
#Data columns (total 2 columns):
#column1name    2 non-null float64
#column2name    2 non-null float64
#dtypes: float64(2)
#memory usage: 48.0+ bytes
df.irow(1) #show the values in the second row
df.iloc[1]
df.iloc[1,:]
df.loc['index2']
df.ix['index2']
#column1name    3.0
#column2name    4.0
df.iloc[:,:1]
df.ix[:,:1]
#         column1name
#index1    1.0
#index2    3.0
df['column1name'] # show column1 values 
#index1    1.0
#index2    3.0
df.iloc[1,0]
df.ix[1,0]
#3
df.ix[[1,0]] # the index change
df.iloc[[1,0]]
df.ix[['index2','index1'],['column1name','column2name']]
df.loc[['index2','index1'],['column1name','column2name']]
#         column1name  column2name
#index2     3.0          4.0
#index1     1.0          2.0
df[:1] 
df.ix[:1]
         column1name  column2name
#index1     1.0           2.0

##can use df.ix too
df.loc[df['column1name']>0]# show all rows that the values in df['column1name'] > 0
df.loc[df['column1name']==0,'column2name'] #show all rows that  the values in df['column1name'] = 0, only show column2name column
df.loc[np.isclose(df['column1name'],0),'column2name']#show all rows that  the values in df['A'] = 0, only show B column

df.values #become array
#array([[ 1.,  2.],
#       [ 3.,  4.]])
df.index #show index list
#Index([u'index1', u'index2'], dtype='object')
df.index.map(str.upper)#(str.lower) or (str.title)
#array(['INDEX1', 'INDEX2'], dtype=object)
df.astype(int)
#         column1name  column2name  
#index1      1             2
#index2      3             4
df['column1name'].dtype #dtype('float64')
df.columns#show column name list
#Index([u'column1name', u'column2name'], dtype='object')
df.index.name='Indexlevel' 
df.columns.name='Columnlevel'
#Clumnlevel  column1name  column2name
#Indexlevel
#index1         1.0        2.0
#index2         3.0        4.0
df.rename(index={'index1':'index1_newname'}, columns={'column1name':'column1name_newname'},inplace=True)
df.rename(index=str.upper,columns=str.upper, inplace=True)
#                 COLUMN1NAME_NEWNAME    COLUMN2NAME
#INDEX1_NEWNAME          1.0             2.0
#INDEX2                  3.0             4.0

#shuffle rows
df=df.reindex(np.random.permutation(df.index))
df=df.take(np.random.permutation(len(df)))

df=df.reindex(index=['index2','index1'], columns=['column2name','column3name'],method='ffill')
#         column2name  column3name
#index2     4.0         NaN
#index1     2.0         NaN
#fill_value=0, method :'bfill' (or ’ffill’, 'nearest')
#ffill: use last valid value to fill missing value #bfill: next valid value # nearest: nearest valid value
df=df.reset_index()
#    index    column1name   column2name
#0   index1      1.0           2.0
#1   index2      3.0           4.0
df=df.set_index(['column1name','column2name' ], drop=False)#the unique values in column1 and column2 become two-level indexes 
#if drop=True, the new columns won't include the column1 and column2
#                          column1name   column2name
#column1name  column2name
#   1.0          2.0           1.0          2.0
#   3.0          4.0           3.0          4.0
####################################################################################
df=pd.DataFrame([[1,np.nan],[3,4]],index=['index1','index2'],
             columns=['column1name','column2name'], dtype='float')
#         column1name  column2name  
#index1      1.0         NaN
#index2      3.0         4.0

df.dropna(inplace=True)
#          column1name  column2name
#index2       3.0         4.0
df.dropna(subset=['column1name'],inplace=True) 
#   column1name  column2name  
#index1      1.0         NaN
#index2      3.0         4.0
df.dropna(axis=1,inplace=True)
#        column1name
#index1    1.0
#index2    3.0
df.dropna(how='all', thresh=None,inplace=True)
#how='all'('any'), drop a row that are all NA
#thresh=int value : you specify a minimum number of non-null values for the row/column to be kept
df.fillna(0,inplace=True)#_=
df['column2name'].fillna(df['column2name'].mean(), inplace=True)#, df['A'] will be replaced#
df.fillna({'column2name':-1},inplace=True)#, replace nan with -1 in the 'column2name' column
df.fillna(method='ffill',inplace=True) #ffill: use last valid value to fill missing value
#method={‘bfill’,‘ffill’}, #bfill: next valid value
df.isnull()
#         column1name    column2name
#index1    False           True
#index2    False           False
df.isnull().any(axis=0)
#column1name    False
#column2name     True
df.isnull().sum(axis=0)#show how many nan in each feature
#column1name    0
#column2name    1
df.notnull()
#        column1name   column2name
#index1    True          False
#index2    True          True
####################################################################################
df=pd.DataFrame([[1,2],[2,4],[3,6],[4,10]],columns=['column1name','column2name'], dtype='float')
#     column1name  column2name
#0       1.0         2.0
#1       2.0         4.0
#2       3.0         6.0
#3       4.0         10.0
df.corr()#show correlation between two variables(two columns)
#              column1name  column2name
#column1name    1.000000     0.982708
#column2name    0.982708     1.000000 1
df.column1name.corr(df.column2name)#=0.98270762982399085
df.corrwith(df.column1name)#show correlation values between column1 and other columns
#column1name    1.000000
#column2name    0.982708
df.cov()#show the covariance between two variables(columns)
#              column1name   column2name
#column1name    1.666667     4.333333
#column2name    4.333333    11.666667

df.skew() #show each feature skew number# less skew means feature value close to 0
#column1name    0.000000
#column2name    0.752837
from scipy.stats import skew
skew(df, axis=0) #show each feature's skewness
#array([ 0.        ,  0.43465076])
          
df.sum()
#column1name    10.0
#column2name    22.0
df.sum(axis=1, skipna=True)
#0     3.0
#1     6.0
#2     9.0
#3    14.0
df.mean(axis=1, skipna=True)
df.mad(axis=1, skipna=True) #show sum(abs(xi-meanx))/number of x (mean absolute deviation of the values) for each column (row) 
df.var(axis=1, skipna=True) #show sum((xi-meanx)**2)/(number of x -1)
df.std(axis=1, skipna=True) #show sqrt(var) for each column
df.median(axis=1, skipna=True)# show the median value in each column
df.max(axis=1, skipna=True) #show the largest value in each column
df.min(axis=1, skipna=True) #show the smallest value in each column
df.pct_change()#if the values in a column are 1,2,3, it will become NaN, (2-1)/1, (3-2)/2
#     column1name  column2name
#0         NaN         NaN
#1     1.000000     1.000000
#2     0.500000     0.500000
#3     0.333333     0.666667
df['column1name']/df['column1name'].shift(1)-1
df['column1name'].pct_change()
#0         NaN
#1    1.000000
#2    0.500000
#3    0.333333
(df==0).sum(axis=1) # how many zeros in each row
#0    0
#1    0
#2    0
#3    0
df.count()#count non_NA values for each columns
#column1name    4
#column2name    4
df.cumprod(skipna=True)
df.cumsum(skipna=True)# if the values in a column are 1,2,3, it will become 1, 3, 6
#     column1name  column2name
#0       1.0         2.0
#1       3.0         6.0
#2       6.0        12.0
#3      10.0        22.0
df.quantile([0,0.5,1]) # 0(show minvalue) ,1(show maxvalue),0.5(median value)
#      column1name   column2name
#0.0      1.0           2.0
#0.5      2.5           5.0
#1.0      4.0          10.0
####################################################################################
df=pd.DataFrame([[1,5.0],[10,4],[5,10]],index=['index2','index1','index3'],
             columns=['column1name','column2name'], dtype='float')
#         column1name   column2name
#index2      1.0          5.0
#index1      10.0         4.0
#index3      5.0          10.0
df.sort_values(by='column1name',ascending=True, inplace=True)  #Sort by the values along either axis
df.sort_index(by='column1name',ascending=True, inplace=True)
#        column1name   column2name
#index2    1.0           5.0
#index3    5.0          10.0
#index1    10.0          4.0
#(by=['column1name','column2name']) sort by the values in column1name first and then column2name if column1name have the same values
df.rank(axis= 0)#replace each value with its ranking along axis 0 or 1, the ranking of the smallest value is 1
#        column1name   column2name
#index2     1.0          2.0
#index1     3.0          1.0
#index3     2.0          3.0
df.idxmax(axis= 0, skipna=True)#show an index that has the largest value in each column
#column1name    index1
#column2name    index3
df.idxmin(axis= 0, skipna=True)#show an index that has the smallest value in each column
df['column1name'].argsort() #will sort the df['column1name'] values 
#index2    0
#index1    2
#index3    1
df['column1name'].argsort()[::-1] 
#index3    1
#index1    2
#index2    0
df['column1name'].isin([1,'g'])#see if each value is 1 or 'g'
#index2     True
#index1    False
#index3    False
#Name: column1name, dtype: bool
df['column1name'].order(ascending=False)#, Sort by the values along either axis#(ascending=False)from largest to smallest
#index1    10.0
#index3     5.0
#index2     1.0
df['column1name'].value_counts().sort_index(axis=0, ascending=True)
#1.0     1
#5.0     1
#10.0    1
#Name: column1name, dtype: int64
df['column1name'].unique()
#array([  1.,  10.,   5.])
df['column1name'].nunique() #3
####################################################################################
df=pd.DataFrame([['one',1],['one',1],['two',2],['one',2]],
             columns=['column1name','column2name'], dtype='float')
#   column1name column2name
#0   one           1
#1   one           1
#2   two           2
#3   one           2
df.duplicated()#see if each row is a duplicate 
#0    False
#1     True
#2    False
#3    False

df.drop_duplicates('column1name')#drop the #1 and #3 rows#keep the first duplicate of column1
#   column1name column2name
#0   one           1
#2   two           2
df.drop_duplicates('column1name',keep='last')#drop the #0 and #1 rows   #keep the last duplicate of column1
#   column1name column2name
#2   two           2
#3   one           2
df.drop_duplicates(['column1name','column2name'])#drop the #1 row   #keep the first duplicate of column1 and column2
#   column1name column2name
#0   one           1
#2   two           2
#3   one           2
####################################################################################
df=pd.DataFrame([[1,10],[2,20],[3,30]],index=['index1','index2','index3'],
                columns=['column1name','column2name'], dtype='float')
#        column1name  column2name
#index1      1.0         10.0
#index2      2.0         20.0
#index3      3.0         30.0
df.values.flatten()
#array([  1.,  10.,   2.,  20.,   3.,  30.])
df.shift(2,axis=0) #move data down by 2 indexes  #(-2,axis=0) move data up by 2 indexes
#       column1name  column2name
#index1      NaN         NaN
#index2      NaN         NaN
#index3      1.0        10.0
df.drop(['index1','index2'], axis=0)
#        column1name  column2name
#index3      3.0         30.0
df.drop(['column1name'], axis=1)
#        column1name  
#index1      1.0        
#index2      2.0         
#index3      3.0 
del df['column1name'] #delete 'column1name' column
df.replace(10, 100,inplace=True) #replace 10 values in df with 100 #([100,1002], np.nan, inplace=True)
#        column1name  column2name
#index1      1.0         100.0
#index2      2.0         20.0
#index3      3.0         30.0
df.replace([1,2], np.nan, inplace=True)
#        column1name  column2name
#index1      NaN         10.0
#index2      NaN         20.0
#index3      3.0         30.0
####################################################################################
df=pd.DataFrame([[1,2],[2,4],[3,6],[4,10]],columns=['column1name','column2name'], dtype='float')
df['column1name'].map(np.log)#log the values in df['column1name']
#0    0.000000
#1    0.693147
#2    1.098612
#3    1.386294
df['column1name'].map({1:'A',3:'B'})
#0      A
#1    NaN
#2      B
#3    NaN
df['column1name'].map(str.lower)#(str.upper)
df['column1name'].map(lambda x: '%.2f' % x)
df.applymap(lambda x: '%.2f')
#0    1.00
#1    2.00
#2    3.00
#3    4.00
df['column1name'].map(lambda x : int(x))
df['column1name'].apply(lambda x : int(x))
df.apply(lambda x: x.max(), axis=0)
#column1name     4.0
#column2name    10.0
df.apply(lambda x: x.min(), axis=0)
df.apply(lambda x : x.dropna(), axis=1) # delete a row that all elements are nan
def g(x): 
    return Series([x.min(),x.max()], index=('min','max'))
df.apply(g)
#      column1name  column2name
#min     1.0           2.0
#max     4.0          10.0
df.apply(pd.value_counts)
#     column1name  column2name
#1.0      1.0         NaN
#2.0      1.0         1.0
#3.0      1.0         NaN
#4.0      1.0         1.0
#6.0      NaN         1.0
#10.0     NaN         1.0
df.apply(pd.value_counts).fillna(0)
df.applymap(lambda x: '%.2f' %x)
####################################################################################
df=pd.DataFrame([[1,2],[3,4],[5,6]],
                index=pd.MultiIndex.from_arrays([['index_1','index_2','index_3'],['index_A','index_C','index_B']], 
            names=['indexlevel1', 'indexlevel2']),
                columns=pd.MultiIndex.from_arrays([['column1','column2'],['columnA','columnB']], 
            names=['columnlevel1', 'columnlevel2']))
#             columnlevel1   column1   column2
#             columnlevel2   columnA   columnB
#indexlevel1  indexlevel2
#index_1      index_A          1        2
#index_2      index_C          3        4
#index_3      index_B          5        6

#df has two-level index, two-level columns
df.index.names     #FrozenList([u'indexlevel1', u'indexlevel2'])
df.columns.names   #FrozenList([u'columnlevel1', u'columnlevel2'])
df.swaplevel(0,1,axis=0)#(i, j, axis), Swap levels i and j in a Multilevel on a particular axis
#             columnlevel1   column1   column2
#             columnlevel2   columnA   columnB
#indexlevel2  indexlevel1
#index_A      index_1          1         2
#index_C      index_2          3         4
#index_B      index_3          5         6


df.sortlevel(1) #sort the level 2 index# original is to sort level 1 index
#             columnlevel1   column1   column2
#             columnlevel2   columnA   columnB
#indexlevel1  indexlevel2
#index_1      index_A          1        2
#index_3      index_B          5        6
#index_2      index_C          3        4
df.sum(level='indexlevel1')#the index level become only level 1
#columnlevel1   column1   column2
#columnlevel2   columnA   columnB
#indexlevel1
#index_1           1        2
#index_2           3        4
#index_3           5        6
df.sum(level='columnlevel1', axis=1)# the column level only become column 1 level
#             columnlevel1   column1   column2
#indexlevel1  indexlevel2
#index_1      index_A          1        2
#index_2      index_C          3        4
#index_3      index_B          5        6
####################################################################################
df=pd.DataFrame([1,2,3,4],
                index=pd.MultiIndex.from_tuples([('one', 'a'), ('one', 'b'),('two', 'a'), ('two', 'b')],names=['indexlevel1', 'indexlevel2']))
#                         0
#indexlevel1 indexlevel2
#one            a        1.0
#               b        2.0
#two            a        3.0
#               b        4.0
df.unstack(0)
#                0
#indexlevel1    one  two
#indexlevel2
#a               1   3
#b               2   4
df.unstack(1)
df.unstack()
df.unstack('indexlevel2')
#                0
#indexlevel2     a  b
#indexlevel1
#one             1  2
#two             3  4

df=pd.DataFrame([[1,2,3,4],[5,6,7,8]],
                columns=pd.MultiIndex.from_tuples([('one', 'a'), ('one', 'b'),('two', 'a'), ('two', 'b')], 
                                                  names=['columnlevel1', 'columnlevel2']))              
#columnlevel1     one    two
#columnlevel2    a  b   a  b
#0               1  2   3  4
#1               5  6   7  8
df.unstack(0)
#columnlevel1  columnlevel2   
#one           a             0    1
#                            1    5
#              b             0    2
#                            1    6
#two           a             0    3
#                            1    7
 #             b             0    4
#                            1    8
df=pd.DataFrame([[1,2],[3,4]],index=['a','b'], columns=['one','two'])
#    one  two
#a    1    2
#b    3    4
df.stack()
#a  one    1
#   two    2
#b  one    3
#   two    4
####################################################################################
df1=pd.DataFrame([[1,2],[3,4]], columns=['one','two'])
#   one  two
#0   1    2
#1   3    4
df2=pd.DataFrame([[10,np.nan],[30,40]], columns=['one','two'])
#    one   two
#0   10    NaN
#1   30    40

df1.append(df2,ignore_index=True)
#    one  two
#0    1   2.0
#1    3   4.0
#2   10   NaN
#3   30  40.0
df1.align(df2, join='inner')
#(   one  two
# 0    1    2
# 1    3    4,    one   two
# 0   10   NaN
# 1   30  40.0)
          
df1+df2
df1.add(df2)
#    one   two
#0   11    2
#1   33    44
df1.add(df2, fill_value=0)
#    one   two
#0   11    2
#1   33    44
df1.sub(df2)
df1.subtract(df2)
#    one   two
#0   -9    NaN
#1   -27   -36
df1.multiply(df2)
df1.div(df2)#the values in df1 / the values in df2
df1.divide(df2)

df1.sum(1)
#0    3
#1    7
df1.div(df1.sum(1), axis=0)##normalize each row
df1.T
#      0  1
#one   1  3
#two   2  4

In [ ]:
s=pd.Series([10,5,20,15],index=['indexa','indexb','indexc','indexd'])
#indexa    10
#indexb     5
#indexc    20
#indexd    15
#dtype: int64

s[::2]   #show every other row
#indexa    10
#indexc    20
s.values #array([10,  5, 20, 15], dtype=int64)
s.index  #Index([u'indexa', u'indexb', u'indexc', u'indexd'], dtype='object')
s.reindex(['indexa','a','indexb'], fill_value=0)#(range(4), method='ffill)
#a          0
#indexa    10
s.name='population'
s.index.name='indexname'
s
#indexname
#indexa    10
#indexb     5
#indexc    20
#indexd    15
#Name: population, dtype: int64
s.describe()
#count     4.000000
#mean     12.500000
#std       6.454972
#min       5.000000
#25%       8.750000
#50%      12.500000
#75%      16.250000
#max      20.000000
s.index.is_unique #True    # see if the index are unique (the same index wont have more than one value)
s.unique()        #array([10,  5, 20, 15], dtype=int64) 
s.rank(ascending=False)#the ranking of the largest value is 1
#indexa    3.0
#indexb    4.0
#indexc    1.0
#indexd    2.0
s.order(ascending=False)
s.sort_values(ascending=False)
#indexc    20
#indexd    15
#indexa    10
#indexb     5
s.sort_index()    #Sort by the index along either axis
#indexa    10
#indexb     5
#indexc    20
#indexd    15
s.value_counts(sort=True, ascending=False)
#15    1
#5     1
#20    1
#10    1
s.quantile([0,0.5,1])# 0(minvalue),1(maxvalue),0.5(median value)
#0.0     5.0
#0.5    12.5
#1.0    20.0
s.isnull()
#indexa    False
#indexb    False
#indexc    False
#indexd    False
s.notnull()
#indexa    True
#indexb    True
#indexc    True
#indexd    True
s.dropna()
#indexa    10
#indexb     5
#indexc    20
#indexd    15
s.drop(['indexa','indexb'])
#indexc    20
#indexd    15
s.fillna(s.mean())
s.fillna(s.median())
s.isin([5,10])
#indexa     True
#indexb     True
#indexc    False
#indexd    False
s.replace(10,100)# replace value 10 with 100#
s.replace([10,5], 100)# replace value 10 and 5 with 100
s.replace({10:100,5:50})#replace 10 with 100, 5 with 50
s.replace([10,5],[100,50])#replace 10 with 100, 5 with 50
#########################################################
s=pd.Series([1,2,3],index=[['indexa','indexb','indexc'],['index1','index2', 'index3']])
#indexa  index1    1
#indexb  index2    2
#indexc  index3    3
s['indexa']#=s[0] show the values in index a
#index1    1
s[0]
s['indexa','index1']
#1
s['indexa':'indexb']
s.ix[['indexa','indexb']]
#indexa  index1    1
#indexb  index2    2
s[:,'index1']#show the values in index1
#indexa    1
s.unstack()
#         index1  index2  index3
#indexa    1.0     NaN     NaN
#indexb    NaN     2.0     NaN
#indexc    NaN     NaN     3.0
#########################################################
s1=pd.Series([1,2],index=['indexa','indexb'])
s2=pd.Series([10,20],index=['indexa','index1'])
s1.add(s2, fill_value=0)
#index1    20.0
#indexa    11.0
#indexb     2.0
#########################################################
s.plot()
s1=s.copy()#s1 is  a copy of s
s.to_frame()#Convert Series to DataFrame
s.to_csv('xx.csv')

In [ ]:
df=pd.DataFrame([['a',1,2],['b',3,4],['c',5,6]],columns=['column1name','column2name','column3name'])
#    column1name  column2name  column3name
#0        a            1           2
#1        b            3           4
#2        c            5           6
pd.melt(df, id_vars=['column1name'], value_vars=['column2name'], var_name='myVarname', value_name='myValname')
#    column1name    myVarname    myValname
#0      a         column2name       1
#1      b         column2name       3
#2      c         column2name       5
#########################################################
df=DataFrame({'A': ['a', 'b', 'a'], 'B': [1, 2, 3]})
pd.get_dummies(df, prefix='X_')
#    B  X__a   X__b
#0   1    1      0
#1   2    0      1
#2   3    1      0
s=pd.Series(['a','b','a'])
pd.get_dummies(s)
#   a   b
#0  1   0
#1  0   1
#2  1   0
#########################################################
df=pd.DataFrame([21,23,25,24],columns=['column1name'], dtype='float')
bins=[20,22,24,26]
group_names = ['Low', 'Good', 'Great']
A=pd.cut(df['column1name'], bins,right=True)
#0    (20, 22]
#1    (22, 24]
#2    (24, 26]
#3    (22, 24]
#Name: column1name, dtype: category
#Categories (3, object): [(20, 22] < (22, 24] < (24, 26]]
pd.value_counts(A)
#(22, 24]    2
#(24, 26]    1
#(20, 22]    1
#Name: column1name, dtype: int64
pd.cut(df['column1name'], bins,right=False)
#0    [20, 22)
#1    [22, 24)
#2    [24, 26)
#3    [24, 26)
#Name: column1name, dtype: category
#Categories (3, object): [[20, 22) < [22, 24) < [24, 26)]
A=pd.cut(df['column1name'], bins,labels=group_names,right=True)
#0      Low
#1     Good
#2    Great
#3     Good
#Name: column1name, dtype: category
#Categories (3, object): [Low < Good < Great]
pd.value_counts(A)
#Good     2
#Great    1
#Low      1
#Name: column1name, dtype: int64
pd.cut(df['column1name'],3, precision=1)
#0      (21, 22.3]
#1    (22.3, 23.7]
#2      (23.7, 25]
#3      (23.7, 25]
#Name: column1name, dtype: category
#Categories (3, object): [(21, 22.3] < (22.3, 23.7] < (23.7, 25]]
pd.qcut(df['column1name'],3) #each bin interval has the same number of data points
#0    [21, 23]
#1    [21, 23]
#2    (24, 25]
#3    (23, 24]
#Name: column1name, dtype: category
#Categories (3, object): [[21, 23] < (23, 24] < (24, 25]]
#########################################################
df=pd.DataFrame([1,2,3,4,5],columns=['column1name'], dtype='float')
####data average method 
pd.rolling_mean(df['column1name'], 3, min_periods=2)#it becomes NaN, NaN, 2(mean of 1+2+3), 3, 4#take 3 values to average
#min_periods=2 for the values are NaN, recalculate by taking 2 values to average, it become NaN 1.5, 2,3,4
#0    NaN
#1    1.5
#2    2.0
#3    3.0
#4    4.0
#Name: column1name, dtype: float64
pd.ewma(df['column1name'], span=2)#exponentially weighted moving average
#alpha=2/1+span, a=1-alpha
#x1, (x2+a*x1)/1+a, (x3+a*x2+(a*a)*x1)/(1+a+a^2), ....#more closer to data distribution than rolling mean
#0    1.000000
#1    1.750000
#2    2.615385
#3    3.550000
#4    4.520661
#Name: column1name, dtype: float64

from scipy.stats import percentileofscore
x=[1, 2, 3, 4]
percentileofscore(x, 3)  #75.0 #100% of 75 members are <= 3

functionA=lambda x: percentileofscore(x, 3)
pd.rolling_apply(df['column1name'], 2, functionA)
#0      NaN
#1    100.0  #how many percentage of 1,2 less than or equal to 3 : 100
#2    100.0  #how many percentage of 2,3 less than or equal to 3 : 100
#3     50.0  #how many percentage of 3,4 less than or equal to 3 : 50
#4      0.0  #how many percentage of 4,5 less than or equal to 3 : 0

df=pd.DataFrame({'column1name':[1,2,3,4,5],'column2name':[10,20,35,40,50]})
pd.rolling_corr(df['column1name'], df['column2name'], 3, min_periods=2)#moving sample correlation
#take every 3 value of df['column1name'] and df['column2name'], calculate their correlation
#0         NaN
#1    1.000000
#2    0.993399
#3    0.960769
#4    0.981981
# fit linear regression
model=pd.ols(y=df['column1name'], x=df['column2name'], window=3)#every 3th row show the linear slope and intercept
model.beta
#        x     intercept
#2   0.078947  0.289474
#3   0.092308  0.076923
#4   0.128571  -1.357143
#########################################################
df1=pd.DataFrame({'df1column2':['a','b','a'],'df1column1':[1,2,3]})
df2=pd.DataFrame({'df2column1':[1,3,2]}, index=['a','b','c'])
#df1                                    df2
#    df1column1       df1column2            df2column1
#0       1                a             a       1
#1       2                b             b       3
#2       3                a             c       2
pd.merge(df1, df2, left_on='df1column2', right_index=True)
#   df1column1         df1column2   df2column1
#0      1                    a          1
#2      3                    a          1
#1      2                    b          3
pd.merge(df1, df2, left_on='df1column2', right_index=True,how='outer')
pd.merge(df1, df2, left_on='df1column2', right_index=True,how='right')#based on df2 key
#   df1column1         df1column2   df2column1
#0      1                    a          1
#2      3                    a          1
#1      2                    b          3
#2     NaN                   c          2
pd.merge(df1, df2, left_on='df1column2', right_index=True,how='left')#based on df1 key
#   df1column1         df1column2   df2column1
#0      1                    a          1
#1      2                    b          3
#2      3                    a          1
pd.merge(df1, df2, left_on='df1column2', right_index=True,how='right')#based on df2 key
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
df1=pd.DataFrame({'key':['a','b','a'],'df1column1':[1,2,3]})
df2=pd.DataFrame({'df2column1':[1,3,2],'key':['a','b','c']})
#df1                                    df2
#    df1column1          key                df2column1   key
#0       1                a             0       1         a
#1       2                b             1       3         b
#2       3                a             2       2         c
pd.merge(df1, df2, on='key')#df1column1 key df2column1,
#   df1column1              key     df2column1
#0      1                    a          1
#2      3                    a          1
#1      2                    b          3
df1.join(df2, lsuffix='_left', rsuffix='_right',how='outer')#df1column1 key_left df2column1 key_right
#    df1column1   key_left   df2column1  key_right
#0       1          a           1           a
#1       2          b           3           b
#2       3          a           2           c
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
df1=pd.DataFrame({'common1':['a','b','a'],'common2':['F', 'M', 'F'],'df1column1':[1,2,3]})
df2=pd.DataFrame({'df2column1':[1,3,2],'common1':['a','b','c'],'common2':['F','M','M']})
#df1                                    df2
#    common1  common2  df1column1       common1   common2  df2column1
#0       a      F          1        0      a         F       1
#1       b      M          2        1      b         M       3
#2       a      F          3        2      c         M       2
pd.merge(df1, df2, on=['common1','common2'])
#  common1  common2  df1column1  df2column1
#0   a        F          1           1
#1   a        F          3           1
#2   b        M          2           3
pd.merge(df1, df2, on='common1', suffixes=('_left','_right'))
#  common1 common2_left df1column1  common2_right   df2column1
#0   a        F            1           F               1
#1   a        F            3           F               1
#2   b        M            2           M               3
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#if the columns in df1 are df1column1 and key1(a, b, a..), index is 0,1,2
#if the columns in df2 are df2column1 and key2(a, b, b..), index is 0,1,2
pd.merge(df1, df2, left_on='key1',right_on='key2')
#key1 df1column1 df2column1 key2
# a                          a  
# a                          a 
# b                          b 

#if df1 has index:a c e, df2 has index: a c d 
pd.merge(df1, df2, left_index=True,right_index=True)
df1.join(df2, how='outer')
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#if the columns in df1 are df1column1 and key1(a, b, a..), index is 0,1,2
#if the columns in df2 are df2column1 and key2(a, b, b..), index is 0,1,2
pd.merge(df1, df2, left_on='key1',right_on='key2')
#key1 df1column1 df2column1 key2
# a                          a  
# a                          a 
# b                          b 

#if df1 has index:a c e, df2 has index: a c d 
pd.merge(df1, df2, left_index=True,right_index=True, how='outer')
df1.join(df2, how='outer')
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
df1=pd.DataFrame({'df1column1':[1,2,3]}, index=['a','b','a'])
df2=pd.DataFrame({'df2column1':[1,3,2]} ,index=['a','b','c'])
#df1                            df2
#    df1column1                 df2column1
#a       1                    a       1
#b       2                    b       3
#a       3                    c       2
pd.merge(df1, df2, left_index=True,right_index=True)
f1.join(df2)
#   df1column1  df2column1
#a      1           1
#a      3           1
#b      2           3
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
df1=pd.DataFrame({'df1column1':[1,2,3]})
df2=pd.DataFrame({'df2column1':[1,3,2]})
df1.join(df2).add_prefix('X_')       
#   X_df1column1  X_df2column1
#0      1             1
#1      2             3
#2      3             2
#########################################################
df1=pd.DataFrame({'df1column1':[1,2,3],'df1column2':[10,20,30]}, index=['a','b','c'])
df2=pd.DataFrame({'df2column1':[100,300],'df2column2':[1000,3000]}, index=['a','c'])
#df1                                 df2
#   df1column1 df1column2            df2column1   df2column2
#a     1         10               a      100          1000
#b     2         20              
#c     3         30               c      300          3000
pd.concat([df1,df2], axis=1, keys=['L1','L2'], names=['columnlevel1','columnlevel2'])
#'columnlevel1'       L1       L1              L2        L2
#'columnlevel2'  df1column1  df1column2     df2column1  df2column2
#   a                1          10             100        1000
#   b                2          20             NaN        NaN
#   c                3          30             300        3000
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
df1=pd.DataFrame({'A':[1,3],'B':[2,4]})
df2=pd.DataFrame({'A':[1]})
#df1                                   df2
#      A         B                      A
#0     1         2               0      1          
#1     3         4      
pd.concat([df1, df2])
#    a  b
#0   1  2
#1   3  4
#0  1  NaN
pd.concat([df1, df2], ignore_index=True)
#    a  b
#0   1  2
#1   3  4
#2   1  NaN
pd.concat([df1, df2], ignore_index=True).fillna(method = 'ffill')
#    a  b
#0   1  2
#1   3  4
#2   1  4
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
s1=pd.Series([1,2], index=['a','c'])
s2=pd.Series([3,4], index=['a','b'])
# s1    s2     
# a 1   a 3   
# c 2   b 4                            
pd.concat([s1,s2])
#a    1
#c    2
#a    3
#b    4
pd.concat([s1,s2], axis=1)
#   0     1
#a  1     3
#b  NaN   4
#c  2.0  NaN
pd.concat([s1,s2], axis=1,join='inner')#join='inner', delete a row that has NaN
#  0    1
#a 1   3
pd.concat([s1,s2], axis=1,join='inner', join_axes=[['a','b']]) #select which index want to show
#   0     1
#a  1     3
#b  NaN   4
 
pd.concat([s1,s2], keys=['one','two'])
#one  a    1
#     c    2
#two  a    3
#     b    4
pd.concat([s1,s2], axis=1, keys=['one','two'])
#  one   two
#a  1     3
#b  Nan   4
#c  2    NaN
#########################################################
df1=pd.DataFrame({'A':[np.nan, 3],'B':[2,4]})
df2=pd.DataFrame({'A':[1,100,200]})
#df1                                   df2
#      A         B                     A
#0     NaN       2               0     1          
#1     3         4               1     100
#                                2     200
                                 
df1.combine_first(df2)#patch miss data of df1 from df2
#      A         B              
#0     1         2                   
#1     3         4  
#2   200.0      NaN
df1.update(df2, overwrite=True)
df1
#      A         B              
#0     1         2                   
#1   100         4 
#########################################################
df=pd.DataFrame({'column1':['a','a','b'],'column2':[10,20,30]})
#df                            
#    column1 column2          
#0     a         1              
#1     a         2              
#2     b         3  
pd.crosstab(df.column1, df.column2)#the unique values of df.column1 is the index,
#column2   10    20   30
#column1
#a         1     1    0
#b         0     0    1
pd.crosstab(df.column1, df.column2, margins=True)
#column2   10    20   30  All
#column1
#a         1     1    0   2
#b         0     0    1   1
#All       1     1    1   3
#########################################################
df=pd.DataFrame({'column1':['a','a','a','b','b','b'],'column2':[10,10,20,20,30,30],'column3':[1,2,3,4,5,6]})
#   column1  column2  column3
#0     a       10       1
#1     a       10       2
#2     a       20       3
#3     b       20       4
#4     b       30       5
#5     b       30       6
df['column3'].groupby(df['column1']).mean()
df.groupby(df['column1'])['column3'].mean()
#column1
#a    2
#b    5
df.groupby(df['column1'],as_index=False)['column3'].mean()
#      column1  column3
#0        a        2
#1        b        5
df['column3'].groupby([df['column1'],df['column2']]).mean()
#column1  column2
#a        10         1.5
#         20         3.0
#b        20         4.0
#         30         5.5
#Name: column3, dtype: float64
df.groupby(df['column1']).mean()
#           column2      column3
#column1
#a         13.333333      2.0
#b         26.666667      5.0
df.groupby('column1').mean().add_prefix('A_') 
#          A_column2     A_column3
#column1
#a         13.333333      2.0
#b         26.666667      5.0
df.groupby('column1').size()#the times appearing
#column1
#a    3
#b    3
df.groupby('column1').quantile(0.5)#(or 1,0, 0.5)
#0.5       column2      column3
#column1
#a         10            2.0
#b         30            5.0
df.groupby('column1').describe()
df.groupby('column1').agg(['mean', 'std'])
#              column2           column3
#          mean        std      mean       std
#column1
#a       13.333333   5.773503    2         1.0
#b       26.666667   5.773503    5         1.0
def functionA(x):
    return x.max()-x.min()
df.groupby('column1').agg(['mean', 'std','max','min','count',functionA, np.var, 'sum'])
df.groupby('column1').agg([('meannewname','mean'), ('stdnewname','std')]) #change mean and std names
df.groupby('column1').agg({'column2':['max','min'],'column3':'sum'})
df.groupby('column1').transform(np.mean)#(functionA)
#    column2     column3
#0   13.333333      2
#1   13.333333      2
#2   13.333333      2
#3   26.666667      5
#4   26.666667      5
#5   26.666667      5
def functionB(df, n=2, column='column2'):
    return df.sort_index(by=column)[-n:]
df.groupby('column1').apply(functionB, n=2, column='column3')
#          column1   column2   column3
#column1
#a       1    a        10         2 
#        2    a        20         3
#b       4    b        30         5
#        5    b        30         6
def functionC(x):
    return {'min':x.min(), 'max':x.max()}
df.groupby('column1').apply(functionC)
#column1
#a    {u'max': [u'a', 20, 3], u'min': [u'a', 10, 1]}
#b    {u'max': [u'b', 30, 6], u'min': [u'b', 20, 4]}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
df=pd.DataFrame(np.arange(1,10).reshape(3,3), index=['Joy','Steve','May'],columns=['F','F','M'])
#         F1  F2  M
#Joy      1   2   3
#Steve    4   5   6 
#May      7   8   9
A={'F':'femal','M':'male',} 
df.groupby(A, axis=1).sum()
#      femal  male
#Joy    3      3
#Steve  9      6
#May    15     9
df.groupby(len).sum() 
#         F  F  M
#3        8  10 12
#5        4   5  6
#########################################################
df=pd.DataFrame({'column1':[1,2,3],'column2':[10,20,30],'column3':['F','F','M'],'column4':['one','two','two'],
                 'column5':['A','A','B']})
#   column1  column2  column3  column4  column5
#0     1       10        F       one       A  
#1     2       20        F       two       A  
#2     3       30        M       two       B     
    
df.pivot_table(['column1', 'column2'], index=['column3', 'column4'], columns=['column5'], aggfunc=np.sum)
#                  column1     column2
#         column5   A    B     A    B
#column3  column4
#F         one     1.0  NaN   10.0  NaN 
#          two     2.0  NaN   20.0  NaN
#M         two     NaN  3.0   NaN   30.0
df.pivot_table(['column1', 'column2'], index=['column3', 'column4'], columns=['column5'], aggfunc=np.sum, 
               margins=True, fill_value=0)

#aggfunc=len , each cell is how many values containing in this cell 


### Datetime

In [ ]:
from datetime import datetime, time
from dateutil.parser import parse
from pandas.tseries.offsets import Day, MonthBegin, MonthEnd
import pytz #for timezone setting

datetime.now()           #datetime.datetime(2017, 8, 28, 11, 22, 34, 66000)
datetime.now().year      #2017
datetime.now().month
datetime.now().day       #28
datetime.now().minute
datetime.now().second
datetime.now().date()    #datetime.date(2017, 8, 28)
datetime.now().time()    #datetime.time(11, 22, 34, 66000)
datetime.now().strftime('%a, %d %b(%m) %Y %H:%M:%S') #'Mon, 28 Aug(08) 2017 11:34:33'
datetime.now().replace(minute=0, second=0)           #datetime.datetime(2017, 8, 28, 11, 0, 0, 346000

T1='2011-01-03';T2='1/3/2011'
datetime.strptime(T1,'%Y-%m-%d')#datetime.datetime(2011, 1, 3, 0, 0)
datetime.strptime(T2,'%m/%d/%Y')#datetime.datetime(2011, 1, 3, 0, 0)
parse(T1)# datetime.datetime(2011, 1, 3, 0, 0)
pd.to_datetime(T2)#Timestamp('2011-01-03 00:00:00')
MonthBegin().rollforward(T1)#Timestamp('2011-02-01 00:00:00')
MonthEnd().rollforward(T1)#Timestamp('2011-01-31 00:00:00')
MonthBegin().rollback(T1)#Timestamp('2011-01-01 00:00:00')
MonthEnd().rollback(T1)#Timestamp('2010-12-31 00:00:00')
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
p=pd.Period('2007', freq='A-JAN');
p.asfreq('M', how='start')#Period('2006-02', 'M')
p.asfreq('M', how='end')#Period('2007-01', 'M')
p.asfreq('B', how='start')#Period('2006-02-01', 'B')
p.asfreq('B', how='end')#Period('2007-01-31', 'B')
p.to_timestamp()#)#Period('2006-02-01', 'B')

p=pd.period_range('2006','2008', freq='A-JAN')
#PeriodIndex(['2006', '2007', '2008'], dtype='period[A-JAN]', freq='A-JAN')
p.asfreq('M', how='end')
#PeriodIndex(['2006-01', '2007-01', '2008-01'], dtype='period[M]', freq='M')
p.asfreq('B', how='end')
#PeriodIndex(['2006-01-31', '2007-01-31', '2008-01-31'], dtype='period[B]', freq='B')
p.to_timestamp(how='end')
#DatetimeIndex(['2006-01-31', '2007-01-31', '2008-01-31'], dtype='datetime64[ns]', freq='A-JAN')
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
datetime(2011,1,2) - pd.offsets.BDay()#Timestamp('2010-12-31 00:00:00')
datetime(2011,1,2) - pd.offsets.Day()#Timestamp('2011-01-01 00:00:00')
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A=pd.date_range('1/1/2000', periods=3, freq='M')#'2000-01-31', '2000-02-29', '2000-03-31'
A.to_period()#PeriodIndex(['2000-01', '2000-02', '2000-03'], dtype='period[M]', freq='M')

B=pd.period_range('1/1/2000', periods=3, freq='M')
#PeriodIndex(['2000-01', '2000-02', '2000-03'], dtype='period[M]', freq='M')
B.to_timestamp(how='end')
#DatetimeIndex(['2000-01-31', '2000-02-29', '2000-03-31'], dtype='datetime64[ns]', freq='M')

A=pd.date_range('1/1/2000', periods=3, freq='D')
#'DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03'], dtype='datetime64[ns]', freq='D')
A.to_period()#PeriodIndex(['2000-01-01', '2000-01-02', '2000-01-03'], dtype='period[D]', freq='D')
A.to_period('M')#PeriodIndex(['2000-01', '2000-01', '2000-01'], dtype='period[M]', freq='M')
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[datetime(2011,1,2),datetime(2011,1,3),datetime(2011,1,4)]
#[datetime.datetime(2011, 1, 2, 0, 0),
# datetime.datetime(2011, 1, 3, 0, 0),
# datetime.datetime(2011, 1, 4, 0, 0)]
pd.DatetimeIndex(['1/2/2011','1/3/2011','1/4/2011'])
#DatetimeIndex(['2011-01-02', '2011-01-03', '2011-01-04'], dtype='datetime64[ns]', freq=None)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#pd.date_range(start, end, periods, freq, normalize, tz)
pd.date_range('1/2/2011', periods=3)
pd.date_range('1/2/2011', periods=3,normalize=True) #if 1/1/2000 6:30:00, set to 1/1/2000 00:00:00, normalized to midnight
pd.date_range('1/2/2011', periods=3,freq='D')
pd.date_range('1/2/2011', '1/4/2011')
pd.date_range(start='1/2/2011', periods=3)
pd.date_range(end='1/4/2011', periods=3)
#DatetimeIndex(['2011-01-02', '2011-01-03', '2011-01-04'], dtype='datetime64[ns]', freq='D')
#freq='8h', '2D', '60T'
#'D' calender day, 'B' business day, 'H' hourly, 'T' Minutely, 'S' secondly, 'L' msec, 'U': microsec
# 'M'   last calendar day of each month, 'BM'   last buiness day of each month
# 'MS' first calendar day of each month, 'BMS' first buiness day of each month
#'W-MON', 'W-TUE', 'W-WED', 'W-THU', 'W-FRI', 'W-SAT', 'W-SUN' weekly on a given day
#'WON-1MON', 'WON-2MON', 'WON-2MON'(the third Monday of each month)
#'Q-JAN: on the dates of 01-31, 04-30, 07-31, 10-31
#'Q-JAN',    'Q-FEB   :quartly dates on the last calendar day of every three month
#'BQ-JAN',  'BQ-FEB   :quartly dates on the last business day of every three month
#'QS-JAN',  'QD-FEB   :quartly dates on the first calendar day of every three month
#'BQS-JAN','BQD-FEB   :quartly dates on the first business day of every three month
#'A-JAN',    'A-FEB   :annual dates on the last calendar day of a given month ex: 'A-JAN' 01-31 every year
#'BA-JAN',  'BA-FEB   :annual dates on the last business day of a given month
#'AS-JAN',  'AS-FEB   :annual dates on the first calendar day of a given month
#'BAS-JAN', 'BAS-FEB   :annual dates on the first business day of a given month
#tz='UTC' (or 'US/Eastern') set time zone
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ts=Series(np.arange(1,5), index=pd.date_range('1/2/2011', periods=4, freq='D'))
#2011-01-02    1
#2011-01-03    2
#2011-01-04    3
#2011-01-05    4
#Freq: D, dtype: int32

ts.truncate(after='1/3/2011')
#2011-01-02    1
#2011-01-03    2
#Freq: D, dtype: int32
ts['2011']#show all data in '2011'
ts['2011-01']
#2011-01-02    1
#2011-01-03    2
#2011-01-04    3
#2011-01-05    4
#Freq: D, dtype: int32
ts.shift(2, freq='D')# data shift down by 2 days
#2011-01-04    1
#2011-01-05    2
#2011-01-06    3
#2011-01-07    4
ts.groupby(MonthEnd().rollforward).mean()
#2011-01-31    2.5
ts.resample('2D', how='mean') #how='sum'
ts.resample('2D', how='mean',closed='left')#closed='left'(default)
ts.resample('2D', how='mean',label='left')#label='left'(default)
#2011-01-02    1.5
#2011-01-04    3.5
#Freq: 2D, dtype: float64
#how='sum'
# how='ohlc' show open(first value), high(max value), low(min value), close(last value)
#how='prod' all values are multiplied together
ts.resample('2D', how='mean',closed='right')
#2010-12-31    1.0
#2011-01-02    2.5
#2011-01-04    4.0
#Freq: 2D, dtype: float64
ts.resample('2D', how='mean',label='right')
#2011-01-04    1.5
#2011-01-06    3.5
#Freq: 2D, dtype: float64
ts.resample('2D', how='mean',loffset='-1D')#all index minus 1 Day
#2011-01-01    1.5
#2011-01-03    3.5
#dtype: float64
ts.groupby(lambda x: x.month).mean()
#1    2.5
#dtype: float64
ts.groupby(lambda x: x.weekday).mean()  #index is Monday, Tus, Wed ...Sunday
#0    2
#1    3
#2    4
#6    1    
#dtype: int32
ts=ts.tz_localize('Europe/London') #set up timezone
#2011-01-02 00:00:00+00:00    1
#2011-01-03 00:00:00+00:00    2
#2011-01-04 00:00:00+00:00    3
#2011-01-05 00:00:00+00:00    4
#Freq: D, dtype: int32
ts=ts.tz_convert('Europe/Moscow')  # convert timezone
#2011-01-02 03:00:00+03:00    1
#2011-01-03 03:00:00+03:00    2
#2011-01-04 03:00:00+03:00    3
#2011-01-05 03:00:00+03:00    4
#Freq: D, dtype: int32
S=pd.date_range('1/2/2011', periods=4, freq='2D') 
#DatetimeIndex(['2011-01-02', '2011-01-04', '2011-01-06', '2011-01-08'], dtype='datetime64[ns]', freq='2D')
ts.asof(S)
#2011-01-02    1.0
#2011-01-04    3.0
#2011-01-06    4.0
#2011-01-08    4.0
#Freq: 2D, dtype: float64
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ts=Series(np.arange(1,3), index=pd.date_range('1/2/2011', periods=2, freq='M'))
#2011-01-31    1
#2011-02-28    2
#Freq: M, dtype: int32
#when large date period resample to small date period
ts.resample('W', fill_method='ffill', limit=2) #only fill the first two missing values, the rest of missing values are NaN
#2011-02-06    1.0
#2011-02-13    1.0
#2011-02-20    NaN
#2011-02-27    NaN
#2011-03-06    2.0
#Freq: W-SUN, dtype: float64
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A=Series(np.arange(5), index=pd.date_range('1/1/2000', periods=5, freq='h'))
#2000-01-01 00:00:00    0
#2000-01-01 01:00:00    1
#2000-01-01 02:00:00    2
#2000-01-01 03:00:00    3
#2000-01-01 04:00:00    4
#Freq: H, dtype: int32
A.between_time('01:00', '03:00')
A.between_time(time(1,0), time(3,0))
#2000-01-01 01:00:00    1
#2000-01-01 02:00:00    2
#2000-01-01 03:00:00    3
#Freq: H, dtype: int32
A.between_time(time(1,0), time(3,0))# the same result
A.at_time(time(3,0))
A[time(3,0)]
#2000-01-01 03:00:00    3
#Freq: H, dtype: int32
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
df=DataFrame({'time':pd.date_range('2/1/2011', periods=2, freq='M')})
#    time
#0  2011-02-28
#1  2011-03-31
pd.DatetimeIndex(df['time']).month  #array([2, 3])
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#time unit: 'Y', 'M', 'W', 'D', 'h', 'm', 's', 'ms', 'us', 'ns'
#64-bit integer in nanosecond
np.datetime64('2009-01-01') - np.datetime64('2008-01-01')  #numpy.timedelta64(366,'D')
np.datetime64('2009') + np.timedelta64(20, 'D')            #numpy.datetime64('2009-01-21')
np.timedelta64(1,'W') / np.timedelta64(1,'D')              #7

### Scipy

In [ ]:
from scipy import polyfit
x=np.array([0,2,3])
y=np.array([0,4,6])
polyfit(x,y,1) #array([  2.00000000e+00,  -7.69185075e-16])
polyfit(x,y,2) #array([  6.15259634e-16,   2.00000000e+00,   1.02558010e-15])  #degree=2 poly

import statsmodels.api as sm
A=sm.OLS(y,x).fit()     #fit a line
print A.params          #[2.]    #show the fitting slope
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
from scipy import poly1d
#if f(x)=3x^2 + x + 5
p=poly1d([3,1,5])
x=[1,2]
p(x) 
#array([ 9, 19])
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
from scipy import linalg
x = np.random.randn(3, 2) 
Umatrix, sigma, Vmatrix= linalg.svd(x, full_matrices=True)
Umatrix
#array([[-0.05896357,  0.99737542, -0.0420186 ],
#       [-0.87946859, -0.03198673,  0.47488088],
#       [ 0.47229048,  0.06495471,  0.87904641]])
np.diag(sigma)
#array([[ 1.46405123,  0.        ],
#       [ 0.        ,  0.54081416]])
Vmatrix
Vmatri
#array([[ 0.99999213, -0.00396835],
#       [-0.00396835, -0.99999213]])
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
from scipy.misc import comb
x = np.array([1, 2])
y = np.array([3, 4])
comb(y, x)#y coose x
#array([ 120.,  210.])

### Others

In [12]:
import time
%time [i for i in range(5)]#will show processing time

Wall time: 0 ns


[0, 1, 2, 3, 4]